const QUESTIONS = (window.QUESTIONS && window.QUESTIONS.length)
  ? window.QUESTIONS
  : [
// ===== Multiple Choice (50) =====
{type:"mc",q:"What is $\\frac{d}{dx}(e^x)$?",o:["$xe^{x-1}$","$e^x$","$e^x \\ln(x)$","$\\frac{e^x}{x}$"],a:1},
{type:"mc",q:"What is $\\frac{d}{dx}(a^x)$ where $a$ is a constant?",o:["$xa^{x-1}$","$a^x$","$a^x \\ln(a)$","$\\frac{a^x}{\\ln(a)}$"],a:2},
{type:"mc",q:"What is $\\frac{d}{dx}(\\ln x)$?",o:["$\\ln x$","$\\frac{1}{x \\ln(10)}$","$x \\ln x$","$\\frac{1}{x}$"],a:3},
{type:"mc",q:"What is $\\frac{d}{dx}(\\log x)$ where $\\log$ denotes the common logarithm?",o:["$\\frac{1}{x}$","$\\frac{1}{x \\ln(a)}$","$\\frac{1}{x \\ln(10)}$","$\\log(x) \\cdot \\ln(10)$"],a:2},
{type:"mc",q:"What is $\\frac{d}{dx}(\\log_a x)$ where $a$ is a constant?",o:["$\\frac{1}{x}$","$\\frac{1}{x \\ln(10)}$","$a^x \\ln(a)$","$\\frac{1}{x \\ln(a)}$"],a:3},
{type:"mc",q:"What is $\\frac{d}{dx}(\\sin x)$?",o:["$-\\sin x$","$\\sec^2 x$","$\\cos x$","$-\\cos x$"],a:2},
{type:"mc",q:"What is $\\frac{d}{dx}(\\cos x)$?",o:["$\\sin x$","$-\\sin x$","$\\sec^2 x$","$-\\cos x$"],a:1},
{type:"mc",q:"What is $\\frac{d}{dx}(\\tan x)$?",o:["$\\sec x \\tan x$","$-\\csc^2 x$","$-\\sin x$","$\\sec^2 x$"],a:3},
{type:"mc",q:"What is $\\frac{d}{dx}(\\cot x)$?",o:["$\\csc^2 x$","$-\\csc^2 x$","$\\sec^2 x$","$-\\sec^2 x$"],a:1},
{type:"mc",q:"What is $\\frac{d}{dx}(\\sec x)$?",o:["$-\\csc x \\cot x$","$\\sec^2 x$","$\\csc x \\cot x$","$\\sec x \\tan x$"],a:3},
{type:"mc",q:"What is $\\frac{d}{dx}(\\csc x)$?",o:["$\\csc x \\cot x$","$-\\sec x \\tan x$","$-\\csc x \\cot x$","$\\sec x \\tan x$"],a:2},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(3e^x)$.",o:["$3xe^{x-1}$","$e^{3x}$","$3e^x \\ln(3)$","$3e^x$"],a:3},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(2^x)$.",o:["$x \\cdot 2^{x-1}$","$2^x \\ln(2)$","$2^x$","$\\frac{2^x}{\\ln(2)}$"],a:1},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(e^{5x})$.",o:["$e^{5x}$","$5xe^{4x}$","$5e^{5x}$","$\\frac{e^{5x}}{5}$"],a:2},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(5^{2x})$.",o:["$5^{2x} \\ln(5)$","$2 \\cdot 5^{2x} \\ln(5)$","$2 \\cdot 5^{2x}$","$10 \\cdot 5^{2x}$"],a:1},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(\\ln(x^2+1))$.",o:["$\\frac{1}{x^2+1}$","$\\frac{x}{x^2+1}$","$\\frac{1}{2x}$","$\\frac{2x}{x^2+1}$"],a:3},
{type:"mc",q:"Evaluate $\\frac{d}{dx}[\\log_3(x)]$.",o:["$\\frac{1}{x}$","$\\frac{3}{x}$","$\\frac{1}{x \\ln(3)}$","$\\frac{1}{x \\ln(10)}$"],a:2},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(\\ln(5x+3))$.",o:["$\\frac{1}{5x+3}$","$5 \\ln(5x+3)$","$\\frac{5}{\\ln(5x+3)}$","$\\frac{5}{5x+3}$"],a:3},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(\\ln(x^3-2x))$.",o:["$\\frac{3x^2}{x^3-2x}$","$\\frac{1}{3x^2-2}$","$\\frac{3x^2-2}{x^3-2x}$","$\\frac{3x^2-2}{\\ln(x^3-2x)}$"],a:2},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(\\sin 3x)$.",o:["$\\cos(3x)$","$-3\\cos(3x)$","$3\\sin(3x)$","$3\\cos(3x)$"],a:3},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(\\cos 2x)$.",o:["$-\\sin(2x)$","$2\\sin(2x)$","$-2\\sin(2x)$","$2\\cos(2x)$"],a:2},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(\\tan 5x)$.",o:["$\\sec^2(5x)$","$5\\tan(5x)$","$5\\sec(5x)$","$5\\sec^2(5x)$"],a:3},
{type:"mc",q:"Evaluate $\\frac{d}{dx}(\\sec 2x)$.",o:["$\\sec(2x)\\tan(2x)$","$2\\sec^2(2x)$","$-2\\csc(2x)\\cot(2x)$","$2\\sec(2x)\\tan(2x)$"],a:3},
{type:"mc",q:"For $y^3 + y^2 - 5y - x^2 = -4$, what is $\\frac{dy}{dx}$?",o:["$\\frac{x}{3y^2+2y-5}$","$\\frac{2x}{3y^2-2y+5}$","$\\frac{-2x}{3y^2+2y-5}$","$\\frac{2x}{3y^2+2y-5}$"],a:3},
{type:"mc",q:"For $\\sin y = x$, what is $\\frac{dy}{dx}$?",o:["$\\cos y$","$\\frac{1}{\\sin y}$","$\\frac{1}{\\cos y}$","$-\\cos y$"],a:2},
{type:"mc",q:"According to the handout, which of the following are examples of indeterminate forms?",o:["$\\frac{0}{0}$, $\\frac{\\infty}{\\infty}$, $0 \\cdot \\infty$, $\\infty - \\infty$, $0^0$, $\\infty^0$, $1^\\infty$","$\\frac{0}{0}$ and $\\frac{\\infty}{\\infty}$ only","$0 \\cdot \\infty$ and $\\infty - \\infty$ only","$\\frac{1}{0}$ and $\\frac{0}{1}$"],a:0},
{type:"mc",q:"Evaluate $\\lim_{x \\to -2} \\frac{x+2}{x^2+3x+2}$ using L'Hôpital's Rule.",o:["$0$","$1$","$\\infty$","$-1$"],a:3},
{type:"mc",q:"What is $\\frac{d(3y^2)}{dx}$ when differentiating implicitly with respect to $x$?",o:["$6y$","$3y^2 \\frac{dy}{dx}$","$6 \\frac{dy}{dx}$","$6y \\frac{dy}{dx}$"],a:3},
{type:"mc",q:"What does $\\lim_{x \\to -\\infty} xe^x$ evaluate to?",o:["$\\infty$","$-\\infty$","$1$","$0$"],a:3},
{type:"mc",q:"$\\lim_{x \\to \\infty} \\left(1 + \\frac{1}{x}\\right)^x$ equals:",o:["$1$","$\\infty$","$e$","$0$"],a:2},
{type:"mc",q:"Which notation correctly represents the partial derivative of $z$ with respect to $x$?",o:["$\\frac{dz}{dx}$","$z'(x)$","$\\frac{\\partial z}{\\partial x}$","$\\frac{\\delta z}{\\delta x}$"],a:2},
{type:"mc",q:"For $z = f(x,y)$, to find $\\frac{\\partial z}{\\partial x}$, which variable is treated as constant?",o:["$x$","Neither variable","Both $x$ and $y$","$y$"],a:3},
{type:"mc",q:"For $z = 3x - x^2y^2 + 2x^3y$, what is $\\frac{\\partial z}{\\partial x}$?",o:["$-2x^2y + 2x^3$","$3 + 2xy^2 + 6x^2y$","$-2xy^2 + 6x^2$","$3 - 2xy^2 + 6x^2y$"],a:3},
{type:"mc",q:"For $z = 3x - x^2y^2 + 2x^3y$, what is $\\frac{\\partial z}{\\partial y}$?",o:["$3 - 2xy^2 + 6x^2y$","$-2x^2y + 2x^3$","$2x^3 + 2x^2y$","$-2xy^2 + 2x^3y$"],a:1},
{type:"mc",q:"For $T(x,y,z) = 100 - x^2 - y^2 - z^2$, what is $\\frac{\\partial T}{\\partial x}$?",o:["$-2y$","$100 - 2x$","$-2z$","$-2x$"],a:3},
{type:"mc",q:"For $T(x,y,z) = 100 - x^2 - y^2 - z^2$, evaluate $\\frac{\\partial T}{\\partial x}$ at point $(2, 1, 3)$.",o:["$-1$","$-6$","$-2$","$-4$"],a:3},
{type:"mc",q:"For $P(x,y) = 500x + 300y - 20x^2 - 10y^2$, what is $\\frac{\\partial P}{\\partial x}$?",o:["$300 - 20y$","$500 + 40x$","$500 - 40x$","$-40x$"],a:2},
{type:"mc",q:"For $P(x,y) = 500x + 300y - 20x^2 - 10y^2$, what is $\\frac{\\partial P}{\\partial y}$?",o:["$500 - 40x$","$300 + 20y$","$-20y$","$300 - 20y$"],a:3},
{type:"mc",q:"For $R(T, C) = kTC^2$, what is $\\frac{\\partial R}{\\partial T}$?",o:["$2kTC$","$kC^2$","$kT$","$2kC^2$"],a:1},
{type:"mc",q:"For $R(T, C) = kTC^2$, what is $\\frac{\\partial R}{\\partial C}$?",o:["$kC^2$","$kT$","$2kC$","$2kTC$"],a:3},
{type:"mc",q:"What is $\\frac{d(2x+3y)}{dx}$ in implicit differentiation?",o:["$2 + 3$","$2x + 3y$","$2 - 3\\frac{dy}{dx}$","$2 + 3\\frac{dy}{dx}$"],a:3},
{type:"mc",q:"What is $\\frac{d(xy^2)}{dx}$ using implicit differentiation?",o:["$2xy$","$y^2 + 2y\\frac{dy}{dx}$","$2xy\\frac{dy}{dx} + y^2$","$x \\cdot 2y$"],a:2},
{type:"mc",q:"$\\lim_{x \\to 0}(\\csc x - \\cot x)$ initially yields which indeterminate form?",o:["$\\frac{0}{0}$","$0 \\cdot \\infty$","$\\frac{\\infty}{\\infty}$","$\\infty - \\infty$"],a:3},
{type:"mc",q:"After transforming $\\lim_{x \\to 0}(\\csc x - \\cot x)$ and applying L'Hôpital's Rule, the result is:",o:["$1$","$\\infty$","$-1$","$0$"],a:3},
{type:"mc",q:"Transcendental functions are defined as functions that cannot be expressed as:",o:["Logarithmic functions","Trigonometric functions","Algebraic functions","Exponential functions"],a:2},
{type:"mc",q:"Which of the following is an example of a transcendental function?",o:["$f(x) = x^3 + 2x - 1$","$f(x) = \\frac{x+1}{x-1}$","$f(x) = \\sqrt{x+1}$","$f(x) = e^x$"],a:3},
{type:"mc",q:"In implicit differentiation, $\\frac{dy}{dx}$ translates to:",o:["The second derivative of $y$","The partial derivative of $y$","The derivative of $x$ with respect to $y$","The derivative of $y$ with respect to $x$"],a:3},
{type:"mc",q:"Which of the following equations is given as an example of implicit form?",o:["$y = 3x^2 - 5$","$y = \\frac{1}{x}$","$y = \\ln x$","$xy = 1$"],a:3},
{type:"mc",q:"When applying L'Hôpital's Rule, how are the numerator and denominator treated?",o:["Differentiated as a single quotient using the quotient rule","Only the numerator is differentiated","Differentiated separately","Only the denominator is differentiated"],a:2},
{type:"mc",q:"L'Hôpital's Rule states: if $\\lim_{x \\to a} \\frac{f(x)}{g(x)} = \\frac{0}{0}$, then the limit equals:",o:["$\\lim_{x \\to a} \\frac{f(x)}{g'(x)}$","$\\lim_{x \\to a} \\frac{f'(x)}{g(x)}$","$\\lim_{x \\to a} [f'(x) - g'(x)]$","$\\lim_{x \\to a} \\frac{f'(x)}{g'(x)}$"],a:3},

// ===== Identification (20) =====
{type:"id",q:"What is $\\frac{d}{dx}(e^x)$? (Write the exact expression)",a:"e^x"},
{type:"id",q:"What is $\\frac{d}{dx}(a^x)$ where $a$ is a constant? (Write in terms of $a$ and $x$)",a:"a^x * ln(a)"},
{type:"id",q:"What is $\\frac{d}{dx}(\\ln x)$? (Write the exact expression)",a:"1/x"},
{type:"id",q:"What is $\\frac{d}{dx}(\\log_a x)$? (Write in terms of $x$ and $a$)",a:"1/(x*ln(a))"},
{type:"id",q:"What is $\\frac{d}{dx}(\\log x)$ for the common logarithm? (Write the exact expression)",a:"1/(x*ln(10))"},
{type:"id",q:"What is $\\frac{d}{dx}(\\csc x)$? (Write the exact expression using csc and cot)",a:"-csc(x)*cot(x)"},
{type:"id",q:"What is $\\frac{d}{dx}(\\sec x)$? (Write the exact expression using sec and tan)",a:"sec(x)*tan(x)"},
{type:"id",q:"Evaluate $\\frac{d}{dx}(e^{5x})$. (Write the exact expression)",a:"5e^(5x)"},
{type:"id",q:"Evaluate $\\frac{d}{dx}(\\sin 3x)$. (Write the exact expression)",a:"3cos(3x)"},
{type:"id",q:"Evaluate $\\frac{d}{dx}(\\ln(5x+3))$. (Write the simplified fraction)",a:"5/(5x+3)"},
{type:"id",q:"Evaluate $\\frac{d}{dx}(\\ln(x^2+1))$. (Write the simplified fraction)",a:"2x/(x^2+1)"},
{type:"id",q:"Evaluate $\\frac{d}{dx}(5^{2x})$. (Write the exact expression with ln)",a:"2*5^(2x)*ln(5)"},
{type:"id",q:"For $y^3 + y^2 - 5y - x^2 = -4$, find $\\frac{dy}{dx}$. (Write as a single fraction)",a:"2x/(3y^2+2y-5)"},
{type:"id",q:"For $\\sin y = x$, find $\\frac{dy}{dx}$. (Write as a fraction)",a:"1/cos(y)"},
{type:"id",q:"Evaluate $\\lim_{x \\to -2} \\frac{x+2}{x^2+3x+2}$ using L'Hôpital's Rule. (Write as an integer)",a:"-1"},
{type:"id",q:"What is $\\lim_{x \\to \\infty} \\left(1 + \\frac{1}{x}\\right)^x$? (Write the exact value)",a:"e"},
{type:"id",q:"For $z = 3x - x^2y^2 + 2x^3y$, find $\\frac{\\partial z}{\\partial x}$. (Write the simplified expression)",a:"3 - 2xy^2 + 6x^2y"},
{type:"id",q:"For $z = 3x - x^2y^2 + 2x^3y$, find $\\frac{\\partial z}{\\partial y}$. (Write the simplified expression)",a:"-2x^2y + 2x^3"},
{type:"id",q:"For $T(x,y,z) = 100 - x^2 - y^2 - z^2$, evaluate $\\frac{\\partial T}{\\partial x}$ at point $(2,1,3)$. (Write as an integer)",a:"-4"},
{type:"id",q:"For $P(x,y) = 500x + 300y - 20x^2 - 10y^2$, find $\\frac{\\partial P}{\\partial x}$. (Write the simplified expression)",a:"500 - 40x"},

// ===== True or False (10) =====
{type:"tf",q:"The derivative of $e^x$ is $e^x$.",a:true},
{type:"tf",q:"$\\frac{d}{dx}(\\cos x) = \\sin x$",a:false},
{type:"tf",q:"$\\frac{d}{dx}(\\ln x) = \\frac{1}{x \\ln(10)}$",a:false},
{type:"tf",q:"Transcendental functions are functions that cannot be expressed as algebraic functions.",a:true},
{type:"tf",q:"In implicit differentiation, $\\frac{d(3y^2)}{dx} = 6y\\frac{dy}{dx}$.",a:true},
{type:"tf",q:"L'Hôpital's Rule requires differentiating the numerator and denominator as a single expression using the quotient rule.",a:false},
{type:"tf",q:"$\\lim_{x \\to \\infty}\\left(1 + \\frac{1}{x}\\right)^x = e$",a:true},
{type:"tf",q:"$\\frac{d}{dx}(\\sec x) = \\sec x \\tan x$",a:true},
{type:"tf",q:"In partial differentiation, $\\frac{\\partial z}{\\partial x}$ treats $y$ as a variable.",a:false},
{type:"tf",q:"$\\frac{d}{dx}(a^x) = a^x \\ln(a)$ for any constant $a$.",a:true},

// ===== Fill in the Blank (10) =====
{type:"fitb",before:"The derivative of $\\cot x$ is",after:".",a:"$-\\csc^2 x$"},
{type:"fitb",before:"$\\frac{d}{dx}(\\log x) =$",after:"where $\\log$ is the common logarithm.",a:"$\\frac{1}{x \\ln(10)}$"},
{type:"fitb",before:"For the general exponential function $a^x$, $\\frac{d}{dx}(a^x) =$",after:"",a:"$a^x \\ln(a)$"},
{type:"fitb",before:"When differentiating implicitly, $\\frac{d(3y^2)}{dx} =$",after:"",a:"$6y\\frac{dy}{dx}$"},
{type:"fitb",before:"If $\\lim_{x \\to a} \\frac{f(x)}{g(x)} = \\frac{0}{0}$, then by L'Hôpital's Rule, the limit equals $\\lim_{x \\to a}$",after:"",a:"$\\frac{f'(x)}{g'(x)}$"},
{type:"fitb",before:"The partial derivative $f_x(x,y) = \\lim_{\\Delta x \\to 0}$",after:"",a:"$\\frac{f(x+\\Delta x,y)-f(x,y)}{\\Delta x}$"},
{type:"fitb",before:"$\\frac{d}{dx}(\\sec x) =$",after:"",a:"$\\sec x \\tan x$"},
{type:"fitb",before:"For $R(T,C) = kTC^2$, $\\frac{\\partial R}{\\partial C} =$",after:"",a:"$2kTC$"},
{type:"fitb",before:"$\\lim_{x \\to \\infty}\\left(1+\\frac{1}{x}\\right)^x =$",after:"",a:"$e$"},
{type:"fitb",before:"The derivative $\\frac{d}{dx}(\\ln(x^2+1)) =$",after:"",a:"$\\frac{2x}{x^2+1}$"},
];