const QUESTIONS = (window.QUESTIONS && window.QUESTIONS.length) ? window.QUESTIONS : [

// ===== Multiple Choice (50) =====

{ type: "mc", q: "What period does the First Industrial Revolution cover?", o: ["1700–1800", "1750–1850", "1800–1900", "1820–1870"], a: 1 },
{ type: "mc", q: "What period does the Second Industrial Revolution cover?", o: ["1820–1880", "1850–1910", "1870–1914", "1880–1920"], a: 2 },
{ type: "mc", q: "Who invented the Spinning Jenny in 1764?", o: ["Eli Whitney", "Henry Cort", "James Hargreaves", "John Loudon McAdam"], a: 2 },
{ type: "mc", q: "The Spinning Jenny is best described as a:", o: ["Iron refining machine", "Multi-spindle spinning frame", "Road construction tool", "Steam-powered loom"], a: 1 },
{ type: "mc", q: "Who developed the Puddling Furnace in 1784?", o: ["James Hargreaves", "Eli Whitney", "Nikolaus Otto", "Henry Cort"], a: 3 },
{ type: "mc", q: "What did the Puddling Furnace produce?", o: ["Cotton fiber", "Wrought iron", "Steel alloys", "Petroleum"], a: 1 },
{ type: "mc", q: "Who developed the Cotton Gin in 1793?", o: ["Henry Cort", "James Hargreaves", "Eli Whitney", "Alexander Graham Bell"], a: 2 },
{ type: "mc", q: "What was the primary function of the Cotton Gin?", o: ["Weaving cotton into cloth", "Separating cotton fibers from seeds", "Dyeing cotton fabric", "Compressing cotton bales"], a: 1 },
{ type: "mc", q: "Who created Macadamized Roads in the 1810s?", o: ["John Loudon McAdam", "Karl Benz", "Thomas Edison", "Guglielmo Marconi"], a: 0 },
{ type: "mc", q: "Macadamized roads used what method for durability?", o: ["Asphalt layers", "Wooden planks", "Compacted stone layers", "Concrete slabs"], a: 2 },
{ type: "mc", q: "Who patented the first practical telephone in 1876?", o: ["Thomas Edison", "Nikolaus Otto", "Guglielmo Marconi", "Alexander Graham Bell"], a: 3 },
{ type: "mc", q: "What did Alexander Graham Bell successfully demonstrate with the telephone?", o: ["Morse code transmission", "Voice transmission", "Image transmission", "Radio signals"], a: 1 },
{ type: "mc", q: "Who developed the four-stroke internal combustion engine in 1876?", o: ["Karl Benz", "Thomas Edison", "Nikolaus Otto", "Joseph Swan"], a: 2 },
{ type: "mc", q: "Who built and patented the first gasoline-powered automobile?", o: ["Nikolaus Otto", "Karl Benz", "Thomas Edison", "Alexander Graham Bell"], a: 1 },
{ type: "mc", q: "In what year did Karl Benz patent the first gasoline-powered automobile?", o: ["1876", "1879", "1886", "1895"], a: 2 },
{ type: "mc", q: "Thomas Edison's light bulb in 1879 improved upon earlier designs by whom?", o: ["Nikolaus Otto", "Joseph Swan", "James Hargreaves", "Guglielmo Marconi"], a: 1 },
{ type: "mc", q: "Edison's light bulb made electric lighting accessible for:", o: ["Only factories", "Only homes", "Homes, factories, and streets", "Only streets"], a: 2 },
{ type: "mc", q: "Who pioneered wireless telegraphy and conducted the first successful radio transmission tests?", o: ["Thomas Edison", "Alexander Graham Bell", "Nikolaus Otto", "Guglielmo Marconi"], a: 3 },
{ type: "mc", q: "In what year did Guglielmo Marconi conduct his first successful radio transmission tests?", o: ["1876", "1879", "1886", "1895"], a: 3 },
{ type: "mc", q: "Which impact of industrialization refers to mass migration to cities causing rapid urban growth?", o: ["Economic Growth", "Labor Changes", "Urbanization", "Environmental Effects"], a: 2 },
{ type: "mc", q: "The rise of labor unions was a result of which industrial impact?", o: ["Urbanization", "Labor Changes", "Economic Growth", "Technological Advancements"], a: 1 },
{ type: "mc", q: "Which industrial impact involves increased pollution and deforestation?", o: ["Economic Growth", "Urbanization", "Labor Changes", "Environmental Effects"], a: 3 },
{ type: "mc", q: "The Digital Age is characterized by the rapid growth of:", o: ["Industrial machines", "Digital technologies, particularly the Internet", "Pharmaceutical drugs", "Agricultural tools"], a: 1 },
{ type: "mc", q: "Cybersecurity refers to the practice of protecting devices, systems, networks, and data from:", o: ["Natural disasters", "Cyber threats such as hacking and malware", "Physical theft", "Power outages"], a: 1 },
{ type: "mc", q: "Which cyber threat involves using digital platforms to harass or intimidate others?", o: ["Identity Theft", "Hacking", "Cyberbullying", "Online Scam"], a: 2 },
{ type: "mc", q: "Identity theft can lead to fraud such as:", o: ["System crashes", "Unauthorized purchases or fake accounts", "Data encryption", "Signal jamming"], a: 1 },
{ type: "mc", q: "A 'phishing' email is an example of which cyber threat?", o: ["Cyberbullying", "Hacking", "Identity Theft", "Online Scam"], a: 3 },
{ type: "mc", q: "Viruses and malware often spread through:", o: ["Strong passwords", "Downloads, emails, or unsafe websites", "Antivirus updates", "Two-factor authentication"], a: 1 },
{ type: "mc", q: "A Trojan horse is an example of:", o: ["Strong password", "Antivirus tool", "Virus/Malware", "Firewall"], a: 2 },
{ type: "mc", q: "Hacking often leads to:", o: ["Better cybersecurity", "Privacy breaches and security concerns", "Improved network speed", "Data recovery"], a: 1 },
{ type: "mc", q: "Which cybersecurity practice involves using letters, numbers, and symbols in a password?", o: ["Install Antivirus Software", "Avoid Suspicious Links", "Use Strong Passwords", "Enable Two-Factor Auth"], a: 2 },
{ type: "mc", q: "Antivirus software protects devices by:", o: ["Blocking all internet traffic", "Scanning files for threats", "Encrypting all data", "Resetting device settings"], a: 1 },
{ type: "mc", q: "Human health is defined as:", o: ["The absence of disease only", "Physical fitness only", "Physical, mental, and social well-being", "Mental wellness only"], a: 2 },
{ type: "mc", q: "Medical advancements are driven by:", o: ["Government mandates only", "Technology, research, and innovation", "Population growth", "Environmental changes"], a: 1 },
{ type: "mc", q: "3D bioprinting is an example of which medical advancement?", o: ["Telemedicine", "Medical Imaging", "Surgical Innovations", "Wearable Health Technology"], a: 2 },
{ type: "mc", q: "Telemedicine allows remote healthcare access using:", o: ["Physical clinics", "Digital tools like video calls", "Home remedies", "Traditional medicine"], a: 1 },
{ type: "mc", q: "Smart patches that measure blood sugar without needles are an example of:", o: ["Telemedicine", "Wearable Health Technology", "Medical Imaging", "Surgical Innovations"], a: 1 },
{ type: "mc", q: "PillCam is an example of which medical advancement?", o: ["Wearable Health Technology", "Surgical Innovations", "Restorative Medical Devices", "Medical Imaging"], a: 3 },
{ type: "mc", q: "What does PillCam do?", o: ["Monitors heart rate", "Captures images inside the digestive tract", "Measures blood sugar", "Transmits brain signals"], a: 1 },
{ type: "mc", q: "Bionic eyes are an example of:", o: ["Medical Imaging", "Telemedicine", "Restorative Medical Devices", "Surgical Innovations"], a: 2 },
{ type: "mc", q: "Which public health area ensures everyone has access to quality healthcare?", o: ["Disease Prevention", "Health Education", "Health Equity", "Medical Imaging"], a: 2 },
{ type: "mc", q: "Disease prevention reduces the spread of illness through:", o: ["Surgery and transplants", "Vaccines and sanitation", "Wearable devices", "Telemedicine"], a: 1 },
{ type: "mc", q: "A pandemic is defined as a disease that:", o: ["Spreads in one community", "Spreads across many countries and affects many people", "Only affects animals", "Is limited to one city"], a: 1 },
{ type: "mc", q: "An epidemic is a disease that spreads in:", o: ["Many countries", "One community or country", "Multiple continents", "The entire world"], a: 1 },
{ type: "mc", q: "Where did the Spanish Flu likely begin?", o: ["Spain", "Philippines", "Kansas, USA", "France"], a: 2 },
{ type: "mc", q: "Why was the Spanish Flu called 'Spanish Flu' even though Spain was not the source?", o: ["It mutated in Spain", "Spain was the first to report on it", "Most deaths occurred in Spain", "Spanish scientists discovered it"], a: 1 },
{ type: "mc", q: "What years did the Spanish Flu pandemic span?", o: ["1914–1918", "1918–1920", "1920–1922", "1916–1919"], a: 1 },
{ type: "mc", q: "COVID-19 is caused by which virus?", o: ["Influenza A", "SARS-CoV-1", "SARS-CoV-2", "MERS-CoV"], a: 2 },
{ type: "mc", q: "When was the first confirmed COVID-19 case in the Philippines?", o: ["March 2020", "February 2020", "December 2019", "January 2020"], a: 3 },
{ type: "mc", q: "What Philippine law was passed to assist in combating COVID-19 and provide financial support?", o: ["Bayanihan to Recover as One Act", "Bayanihan to Heal as One Act", "Universal Health Care Act", "COVID Emergency Relief Act"], a: 1 },

// ===== Identification (20) =====

{ type: "id", q: "Invented by James Hargreaves, this multi-spindle spinning frame allowed workers to produce multiple threads at once.", a: "Spinning Jenny" },
{ type: "id", q: "Developed by Henry Cort, this pioneering iron refining process removed impurities from pig iron.", a: "Puddling Furnace" },
{ type: "id", q: "Developed by Eli Whitney, this machine quickly separated cotton fibers from seeds.", a: "Cotton Gin" },
{ type: "id", q: "Created by John Loudon McAdam, this road construction method used compacted stone layers for better drainage and durability.", a: "Macadamized Roads" },
{ type: "id", q: "Patented by Alexander Graham Bell in 1876, this innovation facilitated real-time conversations over long distances.", a: "Telephone" },
{ type: "id", q: "Developed by Nikolaus Otto in 1876, this enabled a more efficient alternative to steam power.", a: "Internal Combustion Engine" },
{ type: "id", q: "Developed by Thomas Edison in 1879, this breakthrough made electric lighting accessible for homes, factories, and streets.", a: "Incandescent Light Bulb" },
{ type: "id", q: "Guglielmo Marconi pioneered this form of communication and conducted its first successful transmission tests in 1895.", a: "Radio (Wireless Telegraphy)" },
{ type: "id", q: "This refers to the practice of protecting devices, systems, networks, and data from cyber threats such as hacking, data breaches, and malware.", a: "Cybersecurity" },
{ type: "id", q: "This cyber threat occurs when someone steals your personal or financial information and uses it without permission.", a: "Identity Theft" },
{ type: "id", q: "This cyber threat involves using digital platforms to harass or intimidate others.", a: "Cyberbullying" },
{ type: "id", q: "This medical advancement allows remote healthcare access using digital tools like video calls.", a: "Telemedicine" },
{ type: "id", q: "This medical advancement uses a patient's cells to create tissues and organs, reducing rejection and aiding recovery.", a: "3D Bioprinting" },
{ type: "id", q: "A swallowable camera that captures images inside the digestive tract without invasive procedures.", a: "PillCam" },
{ type: "id", q: "This public health pillar ensures everyone has access to quality healthcare.", a: "Health Equity" },
{ type: "id", q: "A disease that spreads across many countries and affects many people.", a: "Pandemic" },
{ type: "id", q: "A disease that spreads in one community or country.", a: "Epidemic" },
{ type: "id", q: "The Philippine law passed to combat COVID-19 and provide financial support.", a: "Bayanihan to Heal as One Act" },
{ type: "id", q: "The virus that caused the COVID-19 pandemic.", a: "SARS-CoV-2" },
{ type: "id", q: "This industrial impact refers to increased pollution, deforestation, and resource consumption contributing to concerns about sustainability.", a: "Environmental Effects" },

// ===== True or False (10) =====

{ type: "tf", q: "The Spinning Jenny was invented by Henry Cort in 1764.", a: false },
{ type: "tf", q: "Karl Benz built and patented the first gasoline-powered automobile in 1886.", a: true },
{ type: "tf", q: "Spain was the origin country of the Spanish Flu.", a: false },
{ type: "tf", q: "The COVID-19 pandemic was caused by the SARS-CoV-2 virus.", a: true },
{ type: "tf", q: "Human health refers only to the absence of disease.", a: false },
{ type: "tf", q: "Guglielmo Marconi conducted the first successful radio transmission tests in 1895.", a: true },
{ type: "tf", q: "Identity theft occurs when someone steals your personal or financial information and uses it without permission.", a: true },
{ type: "tf", q: "The Puddling Furnace was used to produce cotton fibers.", a: false },
{ type: "tf", q: "Telemedicine allows remote healthcare access using digital tools like video calls.", a: true },
{ type: "tf", q: "An epidemic is a disease that spreads across many countries and affects many people.", a: false },

// ===== Fill in the Blank (20) =====

{ type: "fitb", before: "The First Industrial Revolution spans the period", after: ".", a: "1750–1850" },
{ type: "fitb", before: "The Spinning Jenny allowed workers to produce", after: "at once, which significantly increased textile production and reduced costs.", a: "multiple threads" },
{ type: "fitb", before: "The Puddling Furnace produced higher-quality", after: "suitable for industrial machinery, railways, and construction.", a: "wrought iron" },
{ type: "fitb", before: "Macadamized roads used compacted stone layers for better drainage and", after: ", which improved transportation networks.", a: "durability" },
{ type: "fitb", before: "Alexander Graham Bell patented the first practical telephone in", after: ".", a: "1876" },
{ type: "fitb", before: "Karl Benz built and patented the first gasoline-powered automobile in", after: ".", a: "1886" },
{ type: "fitb", before: "Thomas Edison developed the first long-lasting and commercially viable incandescent light bulb in", after: ", improving earlier designs by Joseph Swan.", a: "1879" },
{ type: "fitb", before: "Guglielmo Marconi's work laid the foundation for modern broadcasting and long-distance", after: ".", a: "wireless communication" },
{ type: "fitb", before: "Industrialization boosted production, trade, and economic expansion, creating new industries and", after: ".", a: "job opportunities" },
{ type: "fitb", before: "Cybersecurity refers to the practice of protecting devices, systems, networks, and data from cyber threats such as hacking, data breaches, and", after: ".", a: "malware" },
{ type: "fitb", before: "A 'phishing' email pretending to be from a bank asking for login credentials is an example of an online", after: ".", a: "scam" },
{ type: "fitb", before: "Antivirus software helps protect your devices from viruses and malware by", after: "for threats.", a: "scanning files" },
{ type: "fitb", before: "Human health refers to physical, mental, and", after: "well-being.", a: "social" },
{ type: "fitb", before: "3D bioprinting uses a patient's cells to create tissues and organs, reducing", after: "and aiding recovery.", a: "rejection" },
{ type: "fitb", before: "Smart patches measure blood sugar levels without needles and improve", after: "management.", a: "diabetes" },
{ type: "fitb", before: "Public health improves community well-being through education, policies, and", after: ".", a: "programs" },
{ type: "fitb", before: "A pandemic is when a disease spreads across many countries and affects", after: ".", a: "many people" },
{ type: "fitb", before: "The Spanish Flu likely began in", after: ", USA.", a: "Kansas" },
{ type: "fitb", before: "The first confirmed COVID-19 case in the Philippines was in", after: "2020.", a: "January" },
{ type: "fitb", before: "The", after: "to Heal as One Act was passed to assist in combating COVID-19 and provide financial support.", a: "Bayanihan" },

];