const QUESTIONS = (window.QUESTIONS && window.QUESTIONS.length)
  ? window.QUESTIONS
  : [
  // ===== Multiple Choice (100) =====
  {type:"mc",q:"What is the primary purpose of examining the first and second derivatives of a function in graph sketching?",o:["To find the domain and range of the function","To gain insights into increasing/decreasing behavior, local maxima and minima, points of inflection, and concavity","To determine the x-intercepts and y-intercepts only","To calculate the area under the curve"],a:1},
  {type:"mc",q:"Points on a graph where the slope of the tangent line is zero are called:",o:["Critical values","Inflection points","Stationary points","Turning points"],a:2},
  {type:"mc",q:"At a stationary point, the derivative $\\frac{dy}{dx}$ equals:",o:["1","undefined","-1","0"],a:3},
  {type:"mc",q:"Which of the following correctly describes a turning point?",o:["A point where the derivative is undefined","A point where the function crosses the x-axis","A point where the graph changes from increasing to decreasing or vice versa","A point where the second derivative equals zero"],a:2},
  {type:"mc",q:"According to the handout, point C in Figure 1 is NOT a turning point because:",o:["Its derivative does not exist","Before and after the point, the graph is decreasing or sloping downwards","The slope at that point is positive","It is a point of inflection"],a:1},
  {type:"mc",q:"To the left of a minimum point, $\\frac{dy}{dx}$ is:",o:["Zero","Positive","Negative","Undefined"],a:2},
  {type:"mc",q:"At the minimum point, $\\frac{dy}{dx}$ equals:",o:["-1","1","Undefined","0"],a:3},
  {type:"mc",q:"To the right of a minimum point, $\\frac{dy}{dx}$ is:",o:["Negative","Zero","Undefined","Positive"],a:3},
  {type:"mc",q:"For $f(x) = 2x^2 + 3x + 5$, since the coefficient of $x^2$ is positive, the graph:",o:["Opens downward and has a maximum point","Is a straight line","Opens upward and has a minimum point","Has no extremum"],a:2},
  {type:"mc",q:"To the left of a maximum point, $\\frac{dy}{dx}$ is:",o:["Negative","Zero","Undefined","Positive"],a:3},
  {type:"mc",q:"At the maximum point, $\\frac{dy}{dx}$ equals:",o:["1","-1","Undefined","0"],a:3},
  {type:"mc",q:"To the right of a maximum point, $\\frac{dy}{dx}$ is:",o:["Positive","Zero","Undefined","Negative"],a:3},
  {type:"mc",q:"For $y = -x^2 - 2x + 3$, the graph opens downward because:",o:["The constant term is positive","The coefficient of $x^2$ is negative","The coefficient of $x$ is negative","The function is quadratic"],a:1},
  {type:"mc",q:"If $c$ is a number in the domain of $f$, and either $f'(c) = 0$ or $f'(c)$ is non-existent, then $c$ is called:",o:["An inflection point","A relative extremum","A stationary value","A critical value"],a:3},
  {type:"mc",q:"For $f(x) = x^3 - 3x^2 - 9x + 1$, what is the first derivative $f'(x)$?",o:["$3x^2 - 9$","$x^2 - 6x - 9$","$3x^2 - 6x - 9$","$3x^2 + 6x - 9$"],a:2},
  {type:"mc",q:"For $f(x) = x^3 - 3x^2 - 9x + 1$, the critical points are found by factoring $f'(x) = 3(x+1)(x-3)$. The critical values are:",o:["$x = 1$ and $x = -3$","$x = -1$ and $x = 3$","$x = 1$ and $x = 3$","$x = -1$ and $x = -3$"],a:1},
  {type:"mc",q:"The First Derivative Test is used to determine:",o:["Points of inflection only","The concavity of a function","The maxima and minima of the function","The domain and range of the function"],a:2},
  {type:"mc",q:"The extremum values are points where the function changes from:",o:["Concave to convex","Increasing to decreasing or from decreasing to increasing","Positive to negative","Bounded to unbounded"],a:1},
  {type:"mc",q:"Suppose $f$ is continuous on $[a,b]$ and $c \\in (a,b)$ is a critical number. If $f'(x) > 0$ for all $x \\in (a,c)$ and $f'(x) < 0$ for all $x \\in (c,b)$, then $c$ is a:",o:["Relative minimum","Point of inflection","Saddle point","Relative maximum"],a:3},
  {type:"mc",q:"Suppose $f$ is continuous on $[a,b]$ and $c \\in (a,b)$ is a critical number. If $f'(x) < 0$ for all $x \\in (a,c)$ and $f'(x) > 0$ for all $x \\in (c,b)$, then $c$ is a:",o:["Relative maximum","Point of inflection","Relative minimum","Saddle point"],a:2},
  {type:"mc",q:"If $f'(x)$ has the same sign on $(a,c)$ and $(c,b)$, then $c$ is:",o:["A relative maximum","Not a relative extremum","A relative minimum","A global extremum"],a:1},
  {type:"mc",q:"In the First Derivative Test, Step 1 requires you to:",o:["Find the second derivative","Find the critical points by setting $f'(x)=0$","Test intervals around the critical point","Find the first derivative of the function"],a:3},
  {type:"mc",q:"In the First Derivative Test, if $f'(x)$ changes from positive to negative, the function goes from:",o:["Decreasing to increasing — this is a relative minimum","Concave up to concave down","Increasing to decreasing — this is a relative maximum","Decreasing to decreasing"],a:2},
  {type:"mc",q:"In the First Derivative Test, if $f'(x)$ changes from negative to positive, the point is a:",o:["Relative maximum","Point of inflection","Saddle point","Relative minimum"],a:3},
  {type:"mc",q:"If $f'(x)$ does not change sign at a critical point, that point is:",o:["A global maximum","Not a relative extremum, but can be an inflection point","A relative minimum","A relative maximum"],a:1},
  {type:"mc",q:"For $f(x) = x^3 - 3x^2 + 2$, the first derivative is:",o:["$3x^2 - 6$","$3x - 6x$","$3x^2 + 6x$","$3x^2 - 6x$"],a:3},
  {type:"mc",q:"For $f(x) = x^3 - 3x^2 + 2$, the critical points are $x = 0$ and $x = 2$. Which is correct about $f(0)$?",o:["It is a minimum point because the sign changes from negative to positive","It is neither a max nor min","It is a maximum point because the sign changes from positive to negative","It is a point of inflection"],a:2},
  {type:"mc",q:"For $f(x) = x^3 - 3x^2 + 2$, at $x = 2$, $f'$ changes from negative to positive, so $f(2)$ is:",o:["A point of inflection","A relative maximum","Neither a max nor min","A relative minimum"],a:3},
  {type:"mc",q:"For $f(x) = x^3 - 2x^2 + x - 5$, the first derivative is:",o:["$3x^2 - 4x$","$3x^2 + 4x + 1$","$3x^2 - 4x + 1$","$3x^2 - 2x + 1$"],a:2},
  {type:"mc",q:"For $f(x) = x^3 - 2x^2 + x - 5$, the critical points after factoring $(3x-1)(x-1)=0$ are:",o:["$x = -\\frac{1}{3}$ and $x = -1$","$x = \\frac{1}{3}$ and $x = 1$","$x = 3$ and $x = 1$","$x = \\frac{1}{3}$ and $x = -1$"],a:1},
  {type:"mc",q:"The graph of a cubic function is unbounded, meaning its critical points are called:",o:["Global extrema","Absolute extrema","Relative extremum","Stationary extrema"],a:2},
  {type:"mc",q:"For $f(x) = \\sin^2(x)$ on $(0, 2\\pi)$, the first derivative is:",o:["$\\sin(x)\\cos(x)$","$-2\\sin(x)\\cos(x)$","$\\cos^2(x)$","$2\\sin(x)\\cos(x)$"],a:3},
  {type:"mc",q:"For $f(x) = \\sin^2(x)$ on $(0, 2\\pi)$, critical points occur when $\\sin x = 0$ and $\\cos x = 0$. In the given interval, $\\sin x = 0$ when:",o:["$x = \\frac{\\pi}{2}$","$x = \\frac{3\\pi}{2}$","$x = 2\\pi$","$x = \\pi$"],a:3},
  {type:"mc",q:"For $f(x) = \\sin^2(x)$, using the interval table, which of the following is a relative maximum?",o:["$f(\\pi)$","$f(2\\pi)$","$f\\left(\\frac{\\pi}{2}\\right)$","$f(0)$"],a:2},
  {type:"mc",q:"Definition 2.1 states: $f$ is concave downward on $I$ if:",o:["$f''(x) > 0$","$f'(x) < 0$","$f''(x) = 0$","$f''(x) < 0$"],a:3},
  {type:"mc",q:"Definition 2.1 states: $f$ is concave upward on $I$ if:",o:["$f''(x) < 0$","$f'(x) > 0$","$f''(x) = 0$","$f''(x) > 0$"],a:3},
  {type:"mc",q:"In the Second Derivative Test, Step 1 is to:",o:["Compute the second derivative","Apply the test for each critical point","Find the zeros of $f''(x)$","Find the critical points using the 1st derivative test"],a:3},
  {type:"mc",q:"In the Second Derivative Test, if $f''(x) > 0$ at a critical point, then the point is a:",o:["Point of inflection","Relative maximum","Saddle point","Relative minimum"],a:3},
  {type:"mc",q:"In the Second Derivative Test, if $f''(x) < 0$ at a critical point, then the point is a:",o:["Relative minimum","Point of inflection","Relative maximum","Saddle point"],a:2},
  {type:"mc",q:"In the Second Derivative Test, if $f''(x) = 0$, then:",o:["The point is a relative maximum","The point is always a relative minimum","The test is inconclusive; verify using 1st derivative test or graph analysis","The point is always a point of inflection"],a:2},
  {type:"mc",q:"For $f(x) = x^3 - 3x^2 + 4$, the second derivative is:",o:["$3x - 6$","$6x + 6$","$6x$","$6x - 6$"],a:3},
  {type:"mc",q:"For $f(x) = x^3 - 3x^2 + 4$ with $f''(x) = 6x - 6$, evaluating $f''(0)$ gives $-6$, which means:",o:["The test is inconclusive","$x = 0$ is a relative minimum","$x = 0$ is a point of inflection","$x = 0$ is a relative maximum"],a:3},
  {type:"mc",q:"For $f(x) = x^3 - 3x^2 + 4$ with $f''(x) = 6x - 6$, evaluating $f''(2) = 6$ indicates:",o:["$x = 2$ is a relative maximum","$x = 2$ is a point of inflection","The test is inconclusive","$x = 2$ is a relative minimum"],a:3},
  {type:"mc",q:"For $f(x) = \\cos(2x)$, the first derivative is:",o:["$\\sin(2x)$","$2\\sin(2x)$","$-\\sin(2x)$","$-2\\sin(2x)$"],a:3},
  {type:"mc",q:"For $f(x) = \\cos(2x)$, the second derivative is:",o:["$4\\sin(2x)$","$-4\\cos(2x)$","$2\\cos(2x)$","$-2\\cos(2x)$"],a:1},
  {type:"mc",q:"For $f(x) = \\cos(2x)$ with critical points at $x = \\frac{k\\pi}{2}$, when $k$ is odd, $f''(x)$ is positive, so the point is a:",o:["Point of inflection","Relative maximum","Saddle point","Relative minimum"],a:3},
  {type:"mc",q:"For $f(x) = \\cos(2x)$, when $k$ is even, $f''(x)$ is negative, so the point is a:",o:["Relative minimum","Point of inflection","Relative maximum","Saddle point"],a:2},
  {type:"mc",q:"The point of inflection is defined as:",o:["The point where the derivative is zero","The point where the function reaches its maximum value","The section of the curve where the curve shifts its nature from convex to concave or vice versa","The point where the function is undefined"],a:2},
  {type:"mc",q:"Step 1 of locating points of inflection requires you to:",o:["Evaluate the function at solved zeros","Solve for the zeros of the second derivative","Solve for the second derivative, if it exists","Check whether one of the sign-change cases is satisfied"],a:2},
  {type:"mc",q:"Step 2 of locating points of inflection requires you to:",o:["Solve for the second derivative","Solve for the zeros of the second derivative","Check sign-change conditions","Evaluate the function at the solved zeros"],a:1},
  {type:"mc",q:"Step 3 of locating points of inflection requires you to:",o:["Solve for the second derivative","Solve for zeros of $f''$","Check whether the sign-change cases are satisfied","Evaluate the given function at the solved zeros and identify the points of inflection"],a:3},
  {type:"mc",q:"Which condition satisfies a point of inflection at $x = c$? (Case i)",o:["$f''(x) > 0$ if $x < c$, and $f''(x) > 0$ if $x > c$","$f''(x) < 0$ if $x < c$, and $f''(x) < 0$ if $x > c$","$f''(x) < 0$ if $x < c$, and $f''(x) > 0$ if $x > c$","$f''(x) > 0$ if $x < c$, and $f''(x) < 0$ if $x > c$"],a:2},
  {type:"mc",q:"Which condition satisfies a point of inflection at $x = c$? (Case ii)",o:["$f''(x) < 0$ if $x < c$, and $f''(x) < 0$ if $x > c$","$f''(x) > 0$ if $x < c$, and $f''(x) < 0$ if $x > c$","$f''(x) > 0$ if $x < c$, and $f''(x) > 0$ if $x > c$","$f''(x) < 0$ if $x < c$, and $f''(x) > 0$ if $x > c$"],a:1},
  {type:"mc",q:"For $f(x) = x^3$, the second derivative $f''(x)$ is:",o:["$3x$","$x^2$","$6x$","$3x^2$"],a:2},
  {type:"mc",q:"For $f(x) = x^3$, $f''(x) = 6x = 0$ when $x = 0$. Evaluating $f(0)$ gives the point of inflection at:",o:["$(1, 1)$","$(0, 1)$","$(1, 0)$","$(0, 0)$"],a:3},
  {type:"mc",q:"For $g(x) = \\sin x$, the first derivative $g'(x)$ is:",o:["$-\\sin x$","$\\tan x$","$\\cos x$","$-\\cos x$"],a:2},
  {type:"mc",q:"For $g(x) = \\sin x$, the second derivative $g''(x)$ is:",o:["$\\cos x$","$\\sin x$","$-\\cos x$","$-\\sin x$"],a:3},
  {type:"mc",q:"For $g(x) = \\sin x$, $g''(x) = -\\sin x = 0$ when $x = n\\pi$. The point of inflection is at:",o:["$(n\\pi, 1)$","$(0, n\\pi)$","$(0, 0)$","$(n\\pi, n\\pi)$"],a:2},
  {type:"mc",q:"The function $f$ is increasing over an interval if, for all points $x_1$ and $x_2$ in the interval:",o:["$x_1 \\leq x_2 \\rightarrow f(x_1) \\geq f(x_2)$","$x_1 \\geq x_2 \\rightarrow f(x_1) \\leq f(x_2)$","$x_1 \\leq x_2 \\rightarrow f(x_1) \\leq f(x_2)$","$x_1 \\geq x_2 \\rightarrow f(x_1) \\geq f(x_2)$"],a:2},
  {type:"mc",q:"For an increasing function, the value of the function at a larger number is:",o:["Less than the value at a smaller number","Equal to the value at a smaller number","Greater than or equal to the value of the function at a smaller number","Always zero"],a:2},
  {type:"mc",q:"Which of the following is NOT listed as a concept useful in analyzing the graph of a function for curve sketching?",o:["Vertical asymptotes","Points of inflection","Taylor series","Concavity"],a:2},
  {type:"mc",q:"Which of the following IS listed as a concept useful in curve sketching?",o:["Integration by parts","Taylor polynomials","Infinite limits at infinity","Laplace transforms"],a:2},
  {type:"mc",q:"In differential calculus curve sketching, the first step described is:",o:["Choose numbers between critical points and evaluate","Plot points of inflection","Approximately trace the curve","Plot the relative extremum value/s (if any)"],a:3},
  {type:"mc",q:"In differential calculus curve sketching, after plotting extrema and inflection points, Step 3 says to:",o:["Trace the curve immediately","Plot the x-intercepts","Choose at least one number $c$ in between the relative extremum values and points of inflection and evaluate $f(c)$","Find the second derivative"],a:2},
  {type:"mc",q:"When tracing a curve, the handout emphasizes that:",o:["The domain must always be finite","Concavity changes at the point of inflection, and emphasis is given to relative extremum values","All functions must be symmetric","The y-intercept must always be included"],a:1},
  {type:"mc",q:"For $f(x) = x^3 - 2x^2 + x - 5$, the second derivative $f''(x) = 6x - 4$. The point of inflection occurs at $x =$:",o:["$\\frac{1}{3}$","$1$","$\\frac{2}{3}$","$2$"],a:2},
  {type:"mc",q:"For $f(x) = x^4 - 4x^3$, the first derivative is:",o:["$4x^2 - 12x$","$4x^3 - 12x^2$","$x^3 - 12x^2$","$4x^3 - 8x^2$"],a:1},
  {type:"mc",q:"For $f(x) = x^4 - 4x^3$, the critical points from $4x^2(x-3) = 0$ are:",o:["$x = 1$ and $x = 3$","$x = -4$ and $x = 3$","$x = 0$ and $x = 3$","$x = 0$ and $x = 4$"],a:2},
  {type:"mc",q:"For $f(x) = x^4 - 4x^3$, when testing $x = 0$ using interval $(-1, 1)$, the signs of $f'$ do not change, meaning $x = 0$ is:",o:["A relative maximum","Not a relative extremum; it could be a point of inflection","A relative minimum","A global minimum"],a:1},
  {type:"mc",q:"For $f(x) = x^4 - 4x^3$, at $x = 3$ the sign changes from negative to positive, so $x = 3$ is a:",o:["Relative maximum","Point of inflection","Relative minimum","Saddle point"],a:2},
  {type:"mc",q:"For $f(x) = x^4 - 4x^3$, evaluating $f(3)$ gives:",o:["$-27$","$27$","$-81$","$0$"],a:0},
  {type:"mc",q:"For $f(x) = x^4 - 4x^3$, the second derivative is:",o:["$12x - 24$","$12x^2 - 24x$","$12x^2 + 24x$","$12x - 24x^2$"],a:1},
  {type:"mc",q:"For $f(x) = x^4 - 4x^3$, the second derivative $f''(x) = 12x(x-2) = 0$ for $x =$:",o:["$x = 1$ and $x = 3$","$x = 0$ and $x = 2$","$x = -2$ and $x = 0$","$x = 2$ and $x = 4$"],a:1},
  {type:"mc",q:"According to the Applications of Differentiation section, the maxima are described as:",o:["Low points","Turning points only","Peak points","Points of inflection"],a:2},
  {type:"mc",q:"According to the Applications of Differentiation section, the minima are described as:",o:["Peak points","Saddle points","Points where $f'' = 0$","Low points"],a:3},
  {type:"mc",q:"Optimization problems using differentiation are essential for:",o:["Only graphing functions","Finding x-intercepts","Finding maximum profit, minimum cost, greatest area, etc.","Only calculating limits"],a:2},
  {type:"mc",q:"In Step 1 of solving maxima/minima problems, you are told to:",o:["Write the expression to be optimized","Find the derivative","Draw a diagram, label it, and note any restrictions on variables","Set the derivative equal to zero"],a:2},
  {type:"mc",q:"In Step 2 of solving maxima/minima problems, you should:",o:["Test each point for max or min","Draw the diagram","Write an expression for the quantity to be maximized/minimized and form an equation in terms of a single independent variable","Check end point values"],a:2},
  {type:"mc",q:"In Step 3 of solving maxima/minima problems, if $y = f(x)$ is the quantity to maximize/minimize, you find the values of $x$ for which:",o:["$f(x) = 1$","$f''(x) = 0$","$f(x) = 0$","$f'(x) = 0$"],a:3},
  {type:"mc",q:"In Step 4 of solving maxima/minima problems, each point where $f'(x) = 0$ is tested to determine if it is:",o:["A global or local extremum only","A local maximum, local minimum, or neither","An inflection point only","A stationary point only"],a:1},
  {type:"mc",q:"In Step 5 of solving maxima/minima problems, if the function is defined on an interval such as $[a,b]$, you should:",o:["Ignore the end points","Check the values of the function at the end points","Only check the interior critical points","Set the second derivative to zero"],a:1},
  {type:"mc",q:"In Example 1 (rectangle with perimeter 1000 m), with $P = 2x + 2y = 1000$, the width $y$ in terms of $x$ is:",o:["$y = 1000 - x$","$y = 250 - x$","$y = 500 - 2x$","$y = 500 - x$"],a:3},
  {type:"mc",q:"In Example 1, the area function is $A = x(500 - x) = 500x - x^2$. Setting $\\frac{dA}{dx} = 0$ gives $x =$:",o:["$1000$","$500$","$125$","$250$"],a:3},
  {type:"mc",q:"In Example 1, the rectangle with maximum area given perimeter 1000 m turns out to be:",o:["A rectangle with length 400 m and width 100 m","A square with dimensions $s = 250$ m","A rectangle with length 300 m and width 200 m","A square with dimensions $s = 500$ m"],a:1},
  {type:"mc",q:"In Example 2 (farmer with 8 km of fencing, one side is a river), if the two parallel sides are $x$ km each, then $y = $:",o:["$8 - x$","$4 - 2x$","$8 + 2x$","$8 - 2x$"],a:3},
  {type:"mc",q:"In Example 2, the area function is $A(x) = x(8 - 2x)$, which expands to:",o:["$A(x) = 8x - x^2$","$A(x) = 8x + 2x^2$","$A(x) = 8x - 2x^2$","$A(x) = 16x - 2x^2$"],a:2},
  {type:"mc",q:"In Example 2, $A'(x) = -4x + 8 = 0$ gives $x =$:",o:["$4$","$8$","$1$","$2$"],a:3},
  {type:"mc",q:"In Example 2, $A''(x) = -4$. Since $A''(x) < 0$, there is a relative maximum at $(2, 4)$. The maximum area is:",o:["$4 \\ km^2$","$16 \\ km^2$","$2 \\ km^2$","$8 \\ km^2$"],a:3},
  {type:"mc",q:"In Example 2, the dimensions of the land that maximize the area are:",o:["$4 \\ km \\times 2 \\ km$","$8 \\ km \\times 1 \\ km$","$2 \\ km \\times 4 \\ km$","$1 \\ km \\times 8 \\ km$"],a:2},
  {type:"mc",q:"Which concept listed under curve sketching refers to the behavior of a function as $x$ approaches infinity?",o:["Continuity","Differentiability","Symmetry","Infinite limits at infinity"],a:3},
  {type:"mc",q:"Which of the following is a concept listed for curve sketching relating to the function's rate of change?",o:["Domain and range","Symmetry","Differentiability","x-intercepts"],a:2},
  {type:"mc",q:"Concavity of a graph is determined primarily by which derivative?",o:["The original function $f(x)$","The second derivative $f''(x)$","The third derivative $f'''(x)$","The first derivative $f'(x)$"],a:1},
  {type:"mc",q:"A graph is said to be concave upward at point $(c, f(c))$ if, for all values in interval $I$, the point $(x, f(x))$ on the graph is:",o:["Below the tangent line at $(c, f(c))$","On the tangent line at $(c, f(c))$","Undefined at that point","Above the tangent line at $(c, f(c))$"],a:3},
  {type:"mc",q:"Which of the following correctly describes what the derivative of a function tells us?",o:["The area under the curve","The slope or gradient of the graph","The value of the function","The domain of the function"],a:1},
  {type:"mc",q:"For $f(x) = x^3 - 3x^2 + 2$, testing $x = 0$ using $x = -1$ gives $f'(-1) = 9$. Testing with $x = 1.5$ gives $f'(1.5) = -2.25$. What does this sign change indicate?",o:["$f(0)$ is a minimum point","$f(0)$ is a point of inflection","$f(0)$ is neither a max nor min","$f(0)$ is a maximum point"],a:3},
  {type:"mc",q:"For $f(x) = x^3 - 2x^2 + x - 5$ at $x = \\frac{1}{3}$, the relative maximum value $f\\left(\\frac{1}{3}\\right)$ equals:",o:["$-\\frac{131}{27}$","$-5$","$\\frac{131}{27}$","$-\\frac{133}{27}$"],a:0},
  {type:"mc",q:"For $f(x) = x^3 - 2x^2 + x - 5$, the point of inflection is at $x = \\frac{2}{3}$ with $f\\left(\\frac{2}{3}\\right) =$:",o:["$-5$","$-\\frac{133}{27}$","$\\frac{133}{27}$","$-\\frac{131}{27}$"],a:1},
  {type:"mc",q:"For $f(x) = x^4 - 4x^3$, the point of inflection at $x = 2$ gives $f(2) =$:",o:["$0$","$-27$","$-16$","$16$"],a:2},
  {type:"mc",q:"Which step in the First Derivative Test involves setting $f'(x) = 0$ and solving for $x$?",o:["Step 3","Step 1","Step 2","Step 4"],a:2},
  {type:"mc",q:"Which step in the First Derivative Test involves testing intervals around each critical point?",o:["Step 1","Step 4","Step 2","Step 3"],a:3},
  {type:"mc",q:"For the graph of $f(x) = \\sin^2(x)$ on $(0, 2\\pi)$, which of the following is a relative minimum based on the sign table?",o:["$f\\left(\\frac{\\pi}{2}\\right)$","$f\\left(\\frac{3\\pi}{4}\\right)$","$f\\left(\\frac{3\\pi}{2}\\right)$","$f(\\pi)$"],a:3},
  {type:"mc",q:"The process of finding the best possible solution under given constraints using differentiation is referred to as:",o:["Integration","Optimization","Differentiation of higher orders","Linear programming"],a:1},
  {type:"mc",q:"Points A and B in Figure 1 are described as both stationary points AND:",o:["Critical values only","Global extrema","Points of inflection","Turning points"],a:3},
  {type:"mc",q:"For a function with a minimum point, the correct sequence of signs of $\\frac{dy}{dx}$ from left to right is:",o:["Positive, zero, positive","Positive, zero, negative","Negative, zero, negative","Negative, zero, positive"],a:3},
  {type:"mc",q:"For a function with a maximum point, the correct sequence of signs of $\\frac{dy}{dx}$ from left to right is:",o:["Negative, zero, positive","Positive, zero, negative","Negative, zero, negative","Positive, zero, positive"],a:1},

  // ===== True or False (10) =====
  {type:"tf",q:"At a stationary point, the derivative $\\frac{dy}{dx}$ equals zero.",a:true},
  {type:"tf",q:"Point C in Figure 1 is a turning point because the graph is decreasing before and after the point.",a:false},
  {type:"tf",q:"For $f(x) = 2x^2 + 3x + 5$, the function has a maximum point because the coefficient of $x^2$ is positive.",a:false},
  {type:"tf",q:"If $f'(x) > 0$ for all $x \\in (a,c)$ and $f'(x) < 0$ for all $x \\in (c,b)$, then $c$ is a relative maximum.",a:true},
  {type:"tf",q:"If $f''(x) > 0$ at a critical point, the function is concave up and the point is a relative minimum.",a:true},
  {type:"tf",q:"If $f''(x) = 0$ at a critical point, the Second Derivative Test is conclusive and the point is an inflection point.",a:false},
  {type:"tf",q:"The point of inflection is the section of the curve where the curve shifts its nature from convex to concave or vice versa.",a:true},
  {type:"tf",q:"A cubic function has global maxima and minima, not just relative extrema.",a:false},
  {type:"tf",q:"For a decreasing function, $x_1 \\leq x_2$ implies $f(x_1) \\leq f(x_2)$.",a:false},
  {type:"tf",q:"In solving optimization problems, Step 5 requires checking the values of the function at the end points if the function is defined on a closed interval.",a:true},
  {type:"tf",q:"For $f(x) = x^4 - 4x^3$, $x = 0$ is a relative extremum because the first derivative test shows no sign change.",a:false},
  {type:"tf",q:"A rectangle with maximum area for a given perimeter is a square.",a:true}
];