const QUESTIONS = (window.QUESTIONS && window.QUESTIONS.length)
  ? window.QUESTIONS
  : [
  // ===== Multiple Choice (100) =====
  {type:"mc",q:"What does the Multiplication Principle of Counting state?",o:["If there are $n_1$ ways for $E_1$ and $n_2$ ways for $E_2$, then both events have $n_1 \\times n_2$ outcomes","If there are $n_1$ ways for $E_1$ and $n_2$ ways for $E_2$, then both events have $n_1 + n_2$ outcomes","If there are $n_1$ ways for $E_1$ and $n_2$ ways for $E_2$, then both events have $n_1 - n_2$ outcomes","If there are $n_1$ ways for $E_1$ and $n_2$ ways for $E_2$, then both events have $\\frac{n_1}{n_2}$ outcomes"],a:0},
  {type:"mc",q:"When does the Multiplication Principle of Counting work?",o:["Only when all choices are independent of each other","Only when all choices are dependent on each other","When at least one choice is independent","When the number of outcomes is even"],a:0},
  {type:"mc",q:"What is a Permutation?",o:["A counting technique which refers to the arrangement (or ordering) of a set of objects, from first to last, where the order in which the objects are selected does matter","A selection of objects from a collection in any order where order does not matter","A counting technique where objects can repeat","A formula for finding probability of events"],a:0},
  {type:"mc",q:"In a permutation $n$ different objects taken $r$ at a time, which statement is true?",o:["An event cannot repeat","An event can repeat","Order does not matter","$r$ must equal $n$"],a:0},
  {type:"mc",q:"What is the correct formula for permutation $_{n}P_{r}$?",o:["$\\frac{n!}{(n-r)!}$","$\\frac{n!}{r!(n-r)!}$","$\\frac{n!}{r!}$","$n! \\times r!$"],a:0},
  {type:"mc",q:"In the permutation formula $_{n}P_{r} = \\frac{n!}{(n-r)!}$, what does $n$ represent?",o:["The number of objects to choose from","The number of objects selected","The total arrangements","The probability of the event"],a:0},
  {type:"mc",q:"In the permutation formula $_{n}P_{r} = \\frac{n!}{(n-r)!}$, what does $r$ represent?",o:["The number of objects selected","The number of objects to choose from","The factorial of $n$","The sample space"],a:0},
  {type:"mc",q:"Which permutation formula applies when $n$ objects are taken all at a time (n = r)?",o:["$_{n}P_{n} = n!$","$_{n}P_{r} = \\frac{n!}{(n-r)!}$","$_{n}P_{r} = \\frac{n!}{r!(n-r)!}$","$_{n}P_{n} = \\frac{n!}{r!}$"],a:0},
  {type:"mc",q:"In the formula $_{n}P_{n} = n!$, what does $n$ (left of P) represent?",o:["The number of objects to arrange","The number of positions available","The number of objects selected","The sample space size"],a:0},
  {type:"mc",q:"In the formula $_{n}P_{n} = n!$, what does $n$ (right of P) represent?",o:["The number of positions available for the objects to fill","The number of objects to arrange","The number of outcomes","The factorial value"],a:0},
  {type:"mc",q:"What does $n!$ mean in permutation notation?",o:["n factorial","n squared","n times r","n divided by r"],a:0},
  {type:"mc",q:"Which permutation formula applies when some items are look-alikes or duplicates?",o:["$_{n}P_{r} = \\frac{n!}{n_1! \\times n_2! \\times \\ldots \\times n_r!}$","$_{n}P_{r} = \\frac{n!}{(n-r)!}$","$_{n}P_{n} = n!$","$C(n,r) = \\frac{n!}{r!(n-r)!}$"],a:0},
  {type:"mc",q:"In the duplicate permutation formula $_{n}P_{r} = \\frac{n!}{n_1! \\times n_2! \\times \\ldots \\times n_r!}$, what does $n$ represent?",o:["The total number of objects","The first kind of object","The last kind of object","The number selected"],a:0},
  {type:"mc",q:"In the duplicate permutation formula, what does $n_1$ represent?",o:["The first kind","The total objects","The last kind","The number of positions"],a:0},
  {type:"mc",q:"What is a Combination?",o:["A selection of objects from a collection in any order as opposed to permutations which deal with ordered arrangements","An arrangement of objects where order matters","A formula where repetition is allowed","A technique only used for probability"],a:0},
  {type:"mc",q:"Which is the correct formula for combination $C(n,r)$?",o:["$\\frac{n!}{r!(n-r)!}$","$\\frac{n!}{(n-r)!}$","$\\frac{n!}{r!}$","$n! \\times (n-r)!$"],a:0},
  {type:"mc",q:"In the combination formula $C(n,r) = \\frac{n!}{r!(n-r)!}$, what does $n$ represent?",o:["The size of the full set","The number of selected set","The number of set that was left","The probability"],a:0},
  {type:"mc",q:"In the combination formula $C(n,r) = \\frac{n!}{r!(n-r)!}$, what does $r$ represent?",o:["The number of selected set","The size of the full set","The number of set that was left","The total arrangements"],a:0},
  {type:"mc",q:"In the combination formula $C(n,r) = \\frac{n!}{r!(n-r)!}$, what does $(n-r)$ represent?",o:["The number of set that was left","The size of the full set","The number of selected set","The factorial term"],a:0},
  {type:"mc",q:"Which selection rule applies to combinations?",o:["The order of selection does not matter","The order of selection does matter","Objects can be selected more than once","Repetition is allowed"],a:0},
  {type:"mc",q:"Which selection rule about repetition applies to combinations?",o:["Each object can be selected only once; repeat numbers are not allowed","Each object can be selected multiple times","Objects can repeat if they are different types","Repetition is allowed for at most 2 objects"],a:0},
  {type:"mc",q:"What is Probability used to describe?",o:["The phenomenon of chance or randomness of events to occur","The guaranteed outcome of an experiment","The exact number of times an event will happen","The arrangement of objects in a set"],a:0},
  {type:"mc",q:"Which statement correctly defines Probability?",o:["It does not deal with guarantees, but with the likelihood of an occurrence of an event","It guarantees the outcome of an event","It determines the exact number of outcomes","It only applies to mutually exclusive events"],a:0},
  {type:"mc",q:"What is Theoretical or Classical Probability?",o:["Probabilities based on experience and judgment of the person to determine whether a specific outcome is likely to occur","Probability based only on mathematical formulas","Probability determined from past experiments","Probability that events are mutually exclusive"],a:0},
  {type:"mc",q:"Which characteristic distinguishes Theoretical Probability from other types?",o:["It differs from person to person and contains a high degree of personal bias","It is always the same regardless of who calculates it","It is based purely on experimental data","It uses only mathematical equations"],a:0},
  {type:"mc",q:"Which are valid methods for making subjective probability assessments under Theoretical Probability?",o:["Opinion polls, experience, Delphi method","Permutation, combination, and counting","Addition rule, multiplication rule, and complement","Sample space, events, and experiments"],a:0},
  {type:"mc",q:"What is Empirical or Experimental Probability based on?",o:["Examining past data and using logical and mathematical equations involving the data to determine the likelihood of an independent event occurring","Personal judgment and experience only","Theoretical formulas without data","The Delphi method exclusively"],a:0},
  {type:"mc",q:"What does 'Experiment' refer to in probability?",o:["A situation involving chance or probability that produces an event","A guaranteed outcome","An arrangement of objects","A set of all possible results"],a:0},
  {type:"mc",q:"What is the Sample Space (S)?",o:["The set of all possible outcomes of an experiment, that is, any subset of the sample space","A single outcome of an experiment","The probability of an event","One or more outcomes of a single trial"],a:0},
  {type:"mc",q:"What is the sample space when tossing a coin?",o:["$S = \\{head, tail\\}$","$S = \\{1, 2\\}$","$S = \\{0, 1\\}$","$S = \\{H, T, E\\}$"],a:0},
  {type:"mc",q:"What is the sample space when rolling a die?",o:["$S = \\{1, 2, 3, 4, 5, 6\\}$","$S = \\{1, 2, 3, 4, 5\\}$","$S = \\{0, 1, 2, 3, 4, 5, 6\\}$","$S = \\{2, 4, 6\\}$"],a:0},
  {type:"mc",q:"What does Event (E) refer to in probability?",o:["One or more of the possible outcomes of a single trial of an experiment","The set of all possible outcomes","A situation involving chance","The total number of arrangements"],a:0},
  {type:"mc",q:"What is a Simple Event?",o:["When one event occurs","When two or more events occur in a sequence","When events are mutually exclusive","When events are independent"],a:0},
  {type:"mc",q:"What is a Compound Event?",o:["When two or more events occur in a sequence","When one event occurs","When events are mutually exclusive","When events have no outcomes in common"],a:0},
  {type:"mc",q:"Which is an example of a Simple Event?",o:["Probability of getting a Head (H) when a coin is tossed","Probability of getting H in first toss and T in second toss","Probability of drawing two cards in sequence","Probability of rolling two dice"],a:0},
  {type:"mc",q:"Which is an example of a Compound Event?",o:["When two coins are tossed, probability of getting a Head (H) in the first toss and getting a Tail (T) in the second toss","Probability of getting a Head when a coin is tossed","Probability of getting 1 when a die is thrown","Probability of drawing one card"],a:0},
  {type:"mc",q:"What is the Probability Formula for an event happening?",o:["$P(E) = \\frac{n(E)}{n(S)}$","$P(E) = n(E) \\times n(S)$","$P(E) = n(S) - n(E)$","$P(E) = \\frac{n(S)}{n(E)}$"],a:0},
  {type:"mc",q:"What is the formula for the probability of an event NOT happening?",o:["$P(E)' = 1 - P(E)$","$P(E)' = P(E) - 1$","$P(E)' = 1 + P(E)$","$P(E)' = \\frac{1}{P(E)}$"],a:0},
  {type:"mc",q:"What are Mutually Exclusive Events?",o:["When one event occurs, the other cannot, and vice versa (they have no outcomes in common)","When both events can occur at the same time","When one event depends on the other","When events share some common outcomes"],a:0},
  {type:"mc",q:"What is the Addition Rule for two Mutually Exclusive events?",o:["$P(A \\text{ or } B) = P(A) + P(B)$","$P(A \\text{ or } B) = P(A) + P(B) - P(A \\text{ and } B)$","$P(A \\text{ or } B) = P(A) \\times P(B)$","$P(A \\text{ or } B) = P(A) - P(B)$"],a:0},
  {type:"mc",q:"What is the Addition Rule for two events that are NOT Mutually Exclusive?",o:["$P(A \\text{ or } B) = P(A) + P(B) - P(A \\text{ and } B)$","$P(A \\text{ or } B) = P(A) + P(B)$","$P(A \\text{ or } B) = P(A) \\times P(B)$","$P(A \\text{ or } B) = P(A) - P(B) + P(A \\text{ and } B)$"],a:0},
  {type:"mc",q:"What does 'Not Mutually Exclusive Events' mean for the addition rule?",o:["The probability that A or B will occur is the sum of the probabilities of the two events minus the probability that both will occur","The probability is just the sum of both probabilities","The probability is the product of both","The probability that A or B will occur equals 1"],a:0},
  {type:"mc",q:"What are Independent Events?",o:["Events where whatever happens in one event has absolutely nothing to do with what will happen next","Events where the second depends on the first","Events that share common outcomes","Events that are mutually exclusive"],a:0},
  {type:"mc",q:"Which situation describes Independent Events?",o:["The same activity is repeated, but the item that was removed is REPLACED","The item removed is not replaced","The second event depends on what happened first","Events have outcomes in common"],a:0},
  {type:"mc",q:"Which of the following is a characteristic of Independent Events?",o:["The two events are unrelated","The second event's result changes because of the first","Both events must occur simultaneously","Events share at least one outcome"],a:0},
  {type:"mc",q:"What are Dependent Events?",o:["Events where the result of the second event depends upon or will change because of what happened first","Events that are completely unrelated","Events where the item is replaced after each selection","Events with no outcomes in common"],a:0},
  {type:"mc",q:"What is Conditional Probability?",o:["The probability that B will occur given that A has occurred, written P(B|A)","The probability that both A and B occur","The probability that neither A nor B occurs","The probability calculated without any prior information"],a:0},
  {type:"mc",q:"What question does Conditional Probability answer?",o:["What is the chance of an event B happening, given that event A has already happened?","What is the total number of outcomes?","What is the probability of event A alone?","What is the product of probabilities of A and B?"],a:0},
  {type:"mc",q:"How is Conditional Probability of B given A written?",o:["$P(B|A)$","$P(A|B)$","$P(A \\text{ and } B)$","$P(A \\text{ or } B)$"],a:0},
  {type:"mc",q:"What is the Multiplication Rule for both independent and dependent events?",o:["$P(A \\text{ and } B) = P(A) \\times P(B)$","$P(A \\text{ and } B) = P(A) + P(B)$","$P(A \\text{ and } B) = P(A) - P(B)$","$P(A \\text{ and } B) = \\frac{P(A)}{P(B)}$"],a:0},
  {type:"mc",q:"Which counting technique's formula is $\\frac{n!}{(n-r)!}$?",o:["Permutation","Combination","Multiplication Principle","Conditional Probability"],a:0},
  {type:"mc",q:"Which counting technique's formula is $\\frac{n!}{r!(n-r)!}$?",o:["Combination","Permutation","Multiplication Principle","Empirical Probability"],a:0},
  {type:"mc",q:"The key difference between permutation and combination is:",o:["In permutation, order matters; in combination, order does not matter","In permutation, order does not matter; in combination, order matters","Both require order to matter","Neither requires order to matter"],a:0},
  {type:"mc",q:"Which scenario uses permutation rather than combination?",o:["Determining the order in which puppies are sold","Choosing 2 singers from 20 for a duet regardless of order","Selecting a committee from a group","Choosing colors for a design"],a:0},
  {type:"mc",q:"Which scenario uses combination rather than permutation?",o:["Choosing 2 singers from 20 for a duet where order does not matter","Arranging books on a shelf where order matters","Determining order of finishers in a race","Arranging letters of a word"],a:0},
  {type:"mc",q:"In a permutation with duplicates, if you have 9 tiles with 5 blue, 2 gold, and 2 green, what is the denominator of the formula?",o:["$5! \\times 2! \\times 2!$","$5! + 2! + 2!$","$9! \\times 5!$","$2! \\times 2!$"],a:0},
  {type:"mc",q:"How many total possible permutations exist for 9 tiles (5 blue, 2 gold, 2 green)?",o:["756","480","362880","24"],a:0},
  {type:"mc",q:"What value is $_{12}P_4$?",o:["11,880","495","48","1,320"],a:0},
  {type:"mc",q:"What value is $C(20, 2)$?",o:["190","40","380","20"],a:0},
  {type:"mc",q:"What is $5!$?",o:["120","60","24","720"],a:0},
  {type:"mc",q:"What is $3!$?",o:["6","3","9","12"],a:0},
  {type:"mc",q:"What is $2!$?",o:["2","1","4","3"],a:0},
  {type:"mc",q:"If there are 3 main entrées, 4 fruits, and 2 drinks, how many lunch combinations are possible?",o:["24","9","14","12"],a:0},
  {type:"mc",q:"In the Multiplication Principle, if $n(E_1) = 3$ and $n(E_2) = 4$, what is the number of outcomes for both events?",o:["12","7","1","34"],a:0},
  {type:"mc",q:"The probability formula $P(E) = \\frac{n(E)}{n(S)}$ uses $n(S)$ which stands for:",o:["The number of elements in the sample space","The number of favorable events","The number of experiments","The number of independent events"],a:0},
  {type:"mc",q:"The probability formula $P(E) = \\frac{n(E)}{n(S)}$ uses $n(E)$ which stands for:",o:["The number of outcomes in the event","The number of elements in the sample space","The number of experiments","The total number of objects"],a:0},
  {type:"mc",q:"If 45 out of 50 monitors have no defects, what is the probability of randomly choosing one with no defects?",o:["0.9","0.45","0.55","0.1"],a:0},
  {type:"mc",q:"A survey of 30 classes found 5 classes with exactly 2 left-handed students. What is $P(X=2)$?",o:["$\\frac{1}{6}$","$\\frac{5}{6}$","$\\frac{2}{30}$","$\\frac{1}{5}$"],a:0},
  {type:"mc",q:"In the sock drawer problem (1 pair each: blue, brown, red, white, black), what is $P(\\text{red then red})$ with replacement?",o:["$\\frac{1}{25}$","$\\frac{2}{25}$","$\\frac{1}{5}$","$\\frac{1}{10}$"],a:0},
  {type:"mc",q:"There are 6 black pens and 8 blue pens. Without replacement, what is $P(\\text{black, first pick})$?",o:["$\\frac{3}{7}$","$\\frac{6}{13}$","$\\frac{5}{13}$","$\\frac{3}{14}$"],a:0},
  {type:"mc",q:"After picking a black pen (not replaced) from 6 black and 8 blue pens, what is $P(\\text{black, second pick})$?",o:["$\\frac{5}{13}$","$\\frac{6}{14}$","$\\frac{5}{14}$","$\\frac{3}{7}$"],a:0},
  {type:"mc",q:"What is $P(\\text{black and black})$ when drawing two pens without replacement from 6 black and 8 blue pens?",o:["$\\frac{15}{91}$","$\\frac{15}{98}$","$\\frac{30}{91}$","$\\frac{1}{91}$"],a:0},
  {type:"mc",q:"In the probability formula $P(E)' = 1 - P(E)$, what does $P(E)'$ represent?",o:["The probability of the event NOT happening","The probability of the event happening","The conditional probability","The probability of mutually exclusive events"],a:0},
  {type:"mc",q:"Which probability type 'differs from person to person and contains a high degree of personal bias'?",o:["Theoretical or Classical Probability","Empirical or Experimental Probability","Conditional Probability","Mutually Exclusive Probability"],a:0},
  {type:"mc",q:"Which probability type is 'based on examining past data and using logical and mathematical equations'?",o:["Empirical or Experimental Probability","Theoretical or Classical Probability","Conditional Probability","Mutually Exclusive Probability"],a:0},
  {type:"mc",q:"In the books example, how many ways can 5 books be arranged ($_{5}P_{5}$)?",o:["120","60","24","720"],a:0},
  {type:"mc",q:"How many ways can 3 specific books be placed in 3 leftmost positions ($_{3}P_{3}$)?",o:["6","3","12","24"],a:0},
  {type:"mc",q:"How many ways can 2 remaining books be arranged in 2 positions ($_{2}P_{2}$)?",o:["2","4","1","6"],a:0},
  {type:"mc",q:"In the 5-book probability problem, how many total successes are possible for placing English, Spanish, and Algebra leftmost?",o:["12","6","24","120"],a:0},
  {type:"mc",q:"What is the probability of placing English, Spanish, and Algebra as the leftmost books out of 5 total books?",o:["10%","5%","25%","1%"],a:0},
  {type:"mc",q:"What is $P(E)$ when there are 24 favorable outcomes and 11,880 total permutations?",o:["0.00202","0.00132","0.202","0.132"],a:0},
  {type:"mc",q:"In the tile problem with 756 total permutations and 1 desired arrangement, what is $P(E)$?",o:["0.00132","0.00202","0.00526","0.01"],a:0},
  {type:"mc",q:"What is $P(E)$ when Kevin and Phoebe are chosen from 20 singers (combination)?",o:["0.00526","0.00202","0.00132","0.526"],a:0},
  {type:"mc",q:"Which formula calculates $_{n}P_{r}$ when $n = 12$ and $r = 4$?",o:["$\\frac{12!}{(12-4)!}$","$\\frac{12!}{4!(12-4)!}$","$\\frac{12!}{4!}$","$12! \\times 4!$"],a:0},
  {type:"mc",q:"Which of the following correctly states the general formula for $_{n}P_{n}$?",o:["$n!$","$\\frac{n!}{(n-r)!}$","$\\frac{n!}{r!(n-r)!}$","$(n-r)!$"],a:0},
  {type:"mc",q:"If an event is repeated with an item whose numbers will not change (e.g., spinners or dice), the events are:",o:["Independent","Dependent","Mutually exclusive","Conditional"],a:0},
  {type:"mc",q:"If the same activity is repeated but the item removed is NOT replaced, the events are:",o:["Dependent","Independent","Mutually exclusive","Compound"],a:0},
  {type:"mc",q:"The notation $P(B|A)$ is read as:",o:["The probability of B given A","The probability of A given B","The probability of A or B","The probability of A and B"],a:0},
  {type:"mc",q:"What does it mean for two events to 'have no outcomes in common'?",o:["They are Mutually Exclusive","They are Independent","They are Dependent","They are Conditional"],a:0},
  {type:"mc",q:"In the lunch combination problem, $E_1$ represents main entrées with $n(E_1) = 3$. What does $E_2$ represent?",o:["Fruits with $n(E_2) = 4$","Drinks with $n(E_2) = 2$","Combinations with $n(E_2) = 24$","Meals with $n(E_2) = 9$"],a:0},
  {type:"mc",q:"In the puppy problem, $n = 12$ means:",o:["There are 12 puppies","There are 12 varieties","There are 12 positions","There are 12 colors"],a:0},
  {type:"mc",q:"In the puppy permutation problem, $r = 4$ means:",o:["There are 4 varieties of puppies to choose from","There are 4 brown puppies","There are 4 positions on the shelf","There are 4 possible outcomes"],a:0},
  {type:"mc",q:"How many favorable outcomes exist for selling all 4 brown puppies first (in any order)?",o:["24","4","12","11880"],a:0},
  {type:"mc",q:"Which method is NOT listed as a way to make subjective probability assessments?",o:["Monte Carlo simulation","Opinion polls","Experience","Delphi method"],a:0},
  {type:"mc",q:"An event is 'repeated with an item whose numbers will not change, such as spinners or dice.' This describes which type of event?",o:["Independent","Dependent","Conditional","Compound"],a:0},
  {type:"mc",q:"Which is the correct computation for $_{9}P_{r}$ with duplicates: 9 tiles (5 blue, 2 gold, 2 green)?",o:["$\\frac{9!}{5! \\times 2! \\times 2!} = 756$","$\\frac{9!}{5! + 2! + 2!} = 756$","$\\frac{9!}{9!} = 1$","$9! = 362880$"],a:0},
  {type:"mc",q:"What is $C(20,2)$ computed as?",o:["$\\frac{20!}{2!(18)!} = 190$","$\\frac{20!}{2!} = 1216451$","$\\frac{20!}{18!} = 380$","$20 \\times 2 = 40$"],a:0},
  {type:"mc",q:"In the Multiplication Principle, events $E_1, E_2, \\ldots$ must be:",o:["Independent of each other","Dependent on each other","Mutually exclusive","Conditional on each other"],a:0},
  {type:"mc",q:"The probability $P(E) = \\frac{24}{11880} = 0.00202$ corresponds to approximately:",o:["0.202%","2.02%","20.2%","0.0202%"],a:0},
  {type:"mc",q:"The probability $P(E) = \\frac{1}{756} = 0.00132$ corresponds to approximately:",o:["0.132%","1.32%","13.2%","0.0132%"],a:0},
  {type:"mc",q:"The probability $P(E) = \\frac{1}{190} = 0.00526$ corresponds to approximately:",o:["0.526%","5.26%","52.6%","0.0526%"],a:0},
  {type:"mc",q:"$P(\\text{red then red}) = \\frac{1}{5} \\times \\frac{1}{5} = \\frac{1}{25}$ equals:",o:["0.04 = 4%","0.4 = 40%","0.004 = 0.4%","0.25 = 25%"],a:0},
  {type:"mc",q:"$P(\\text{black and black}) = \\frac{3}{7} \\times \\frac{5}{13} = \\frac{15}{91}$ equals approximately:",o:["16.483%","6.483%","1.6483%","0.16483%"],a:0},

  // ===== True or False (10) =====
  {type:"tf",q:"The Multiplication Principle of Counting only works when all choices are independent of each other.",a:true},
  {type:"tf",q:"In a permutation, the order in which objects are selected does NOT matter.",a:false},
  {type:"tf",q:"In a combination, each object can be selected more than once.",a:false},
  {type:"tf",q:"The formula $_{n}P_{r} = \\frac{n!}{(n-r)!}$ is used when there are duplicate objects.",a:false},
  {type:"tf",q:"When $n = r$ in a permutation, $_{n}P_{n} = n!$.",a:true},
  {type:"tf",q:"Mutually exclusive events can occur at the same time.",a:false},
  {type:"tf",q:"For mutually exclusive events A and B: $P(A \\text{ or } B) = P(A) + P(B)$.",a:true},
  {type:"tf",q:"For NOT mutually exclusive events: $P(A \\text{ or } B) = P(A) + P(B) - P(A \\text{ and } B)$.",a:true},
  {type:"tf",q:"The Multiplication Rule for probability states $P(A \\text{ and } B) = P(A) \\times P(B)$ for both independent and dependent events.",a:true},
  {type:"tf",q:"Theoretical Probability is the same for every person who calculates it.",a:false},
  {type:"tf",q:"Empirical Probability is based on examining past data and using logical and mathematical equations.",a:true},
  {type:"tf",q:"A Compound Event occurs when only one event takes place.",a:false},
  {type:"tf",q:"The sample space S when rolling a die is $\\{1, 2, 3, 4, 5, 6\\}$.",a:true},
  {type:"tf",q:"Independent events are ones where the item removed is NOT replaced.",a:false},
  {type:"tf",q:"$P(E)' = 1 - P(E)$ gives the probability of an event NOT happening.",a:true}
];