const QUESTIONS = (window.QUESTIONS && window.QUESTIONS.length)
  ? window.QUESTIONS
  : [
  // ===== Multiple Choice (120) =====
  {type:"mc",q:"Simple Interest is defined as a fixed percentage of the principal paid to a depositor or investor each year the principal is left on deposit. It is usually denoted by which variable?",o:["$F$","$P$","$I$","$r$"],a:2},
  {type:"mc",q:"Which of the following is the correct formula for Simple Interest?",o:["$I = P + r + t$","$I = P \\times r \\times t$","$I = \\frac{P}{rt}$","$I = P(1 + rt)$"],a:1},
  {type:"mc",q:"In the simple interest formula $I = Prt$, what does $P$ represent?",o:["Rate","Time","Simple Interest","Principal"],a:3},
  {type:"mc",q:"In the simple interest formula $I = Prt$, what does $r$ represent?",o:["Principal","Rate","Time","Maturity Value"],a:1},
  {type:"mc",q:"In the simple interest formula $I = Prt$, what does $t$ represent?",o:["Principal","Rate","Time","Interest"],a:2},
  {type:"mc",q:"The final amount or Maturity Value $F$ at the end of $t$ years is computed using which formula?",o:["$F = P - I$","$F = P \\times I$","$F = P + I$","$F = \\frac{P}{I}$"],a:2},
  {type:"mc",q:"Which derived formula correctly expresses the Principal $P$ in terms of Simple Interest $I$, rate $r$, and time $t$?",o:["$P = Irt$","$P = \\frac{I}{rt}$","$P = I - rt$","$P = \\frac{rt}{I}$"],a:1},
  {type:"mc",q:"Which derived formula correctly expresses the rate $r$?",o:["$r = \\frac{I}{Pt}$","$r = IPt$","$r = \\frac{P}{It}$","$r = P - It$"],a:0},
  {type:"mc",q:"Which derived formula correctly expresses the time $t$?",o:["$t = \\frac{I}{Pr}$","$t = IPr$","$t = \\frac{P}{Ir}$","$t = Pr - I$"],a:0},
  {type:"mc",q:"The maturity value formula $F = P(1 + rt)$ is derived from which combination?",o:["$F = P - Prt$","$F = P + Prt$","$F = P \\div Prt$","$F = Prt - P$"],a:1},
  {type:"mc",q:"If $P = $ ₱1,500, $r = 8\\%$, and $t = 2$ years, what is the Simple Interest $I$?",o:["₱120","₱240","₱480","₱300"],a:1},
  {type:"mc",q:"If $I = $ ₱300, $r = 9\\%$, and $t = \\frac{1}{3}$ year, what is the Principal $P$?",o:["₱1,000","₱10,000","₱5,000","₱3,000"],a:1},
  {type:"mc",q:"If $I = $ ₱1,912.50, $P = $ ₱9,000, and $t = 2.5$ years, what is the rate $r$?",o:["6%","7.5%","8.5%","10%"],a:2},
  {type:"mc",q:"What is the maturity value $F$ if $P = $ ₱8,000, $t = 1.5$ years, and $r = 10\\%$?",o:["₱8,800","₱9,200","₱9,000","₱9,500"],a:1},
  {type:"mc",q:"Discount $D$ is best described as which of the following?",o:["The interest added to the maturity value","A deduction from maturity amount $F$ of an obligation allowed for paying it currently","The principal amount of a loan","The total amount paid at maturity"],a:1},
  {type:"mc",q:"What is the formula for Simple Discount $D$?",o:["$D = P \\cdot d \\cdot t$","$D = F \\cdot d \\cdot t$","$D = F - P$","$D = F(1 + dt)$"],a:1},
  {type:"mc",q:"In the simple discount formula $D = Fdt$, what does $d$ represent?",o:["Discount amount","Discount rate","Time of discount","Maturity amount"],a:1},
  {type:"mc",q:"In the simple discount formula $D = Fdt$, what does $t$ represent?",o:["Maturity amount","Discount amount","Discount rate","Time or term of discount"],a:3},
  {type:"mc",q:"To find the Present Value $P$ using simple discount, which formula is used?",o:["$P = F + D$","$P = F(1 + dt)$","$P = F(1 - dt)$","$P = \\frac{D}{Ft}$"],a:2},
  {type:"mc",q:"The derived formula for discount rate $d$ in simple discount is:",o:["$d = \\frac{D}{Ft}$","$d = Ft - D$","$d = \\frac{F}{Dt}$","$d = D + Ft$"],a:0},
  {type:"mc",q:"The derived formula for time $t$ in simple discount is:",o:["$t = \\frac{D}{Fd}$","$t = Fd - D$","$t = \\frac{F}{Dd}$","$t = D \\cdot Fd$"],a:0},
  {type:"mc",q:"The derived formula for maturity amount $F$ in simple discount is:",o:["$F = D - dt$","$F = \\frac{D}{dt}$","$F = D \\cdot dt$","$F = D + dt$"],a:1},
  {type:"mc",q:"What is the present value of ₱2,000 due at the end of 90 days at 5% simple discount? (Use $t = \\frac{1}{4}$)",o:["₱1,900","₱1,975","₱1,800","₱1,850"],a:1},
  {type:"mc",q:"Actual Time refers to which of the following?",o:["A method that assumes 30 days per month","The actual number of days between two dates","The time computed using 360 days per year","The approximate number of months in a term"],a:1},
  {type:"mc",q:"Approximate Time is a method that assumes how many days in each month?",o:["28 days","29 days","30 days","31 days"],a:2},
  {type:"mc",q:"Under the Approximate Time method, how many days are assumed in one year?",o:["365 days","366 days","360 days","350 days"],a:2},
  {type:"mc",q:"Exact Interest $I_e$ is a type of simple interest computed based on how many days in a year?",o:["360 days","365 days","366 days","350 days"],a:1},
  {type:"mc",q:"The formula for Exact Interest $I_e$ is:",o:["$I_e = Pr \\frac{d}{360}$","$I_e = Pr \\frac{d}{365}$","$I_e = Pr \\frac{d}{12}$","$I_e = Pr \\cdot d$"],a:1},
  {type:"mc",q:"Ordinary Interest $I_o$ is a type of interest computed based on how many days in a year?",o:["365 days","366 days","360 days","350 days"],a:2},
  {type:"mc",q:"The formula for Ordinary Interest $I_o$ is:",o:["$I_o = Pr \\frac{d}{365}$","$I_o = Pr \\frac{d}{360}$","$I_o = Pr \\cdot d$","$I_o = \\frac{Pr}{360d}$"],a:1},
  {type:"mc",q:"Under Exact Interest, the time for 1 day is equivalent to:",o:["$\\frac{1}{360}$ year","$\\frac{1}{365}$ year","$\\frac{1}{12}$ year","$\\frac{1}{52}$ year"],a:1},
  {type:"mc",q:"Under Ordinary Interest, the time for 1 day is equivalent to:",o:["$\\frac{1}{365}$ year","$\\frac{1}{360}$ year","$\\frac{1}{12}$ year","$\\frac{1}{52}$ year"],a:1},
  {type:"mc",q:"Which combination yields the HIGHEST interest amount?",o:["Exact Interest using Approximate Time","Exact Interest using Actual Time","Ordinary Interest using Approximate Time","Ordinary Interest using Actual Time"],a:3},
  {type:"mc",q:"Compound Interest is denoted by which variable?",o:["$I$","$I_e$","$I_o$","$I_c$"],a:3},
  {type:"mc",q:"Compound Interest is best defined as interest computed on:",o:["The original principal only","The interest accumulated only","The sum of the original principal and the interest accumulated","The maturity value minus the discount"],a:2},
  {type:"mc",q:"The frequency of conversion, denoted by $m$, is:",o:["The number of years of the loan","The number of times interest is computed in one year","The total number of conversion periods","The nominal rate divided by time"],a:1},
  {type:"mc",q:"The total number of conversion periods $n$ for a compound interest term is computed as:",o:["$n = \\frac{t}{m}$","$n = t + m$","$n = tm$","$n = \\frac{m}{t}$"],a:2},
  {type:"mc",q:"If interest is compounded annually, the frequency of conversion $m$ equals:",o:["12","4","2","1"],a:3},
  {type:"mc",q:"If interest is compounded semiannually, the frequency of conversion $m$ equals:",o:["1","2","4","12"],a:1},
  {type:"mc",q:"If interest is compounded quarterly, the frequency of conversion $m$ equals:",o:["1","2","4","12"],a:2},
  {type:"mc",q:"If interest is compounded monthly, the frequency of conversion $m$ equals:",o:["1","4","6","12"],a:3},
  {type:"mc",q:"If $t = 3$ years and interest is compounded semiannually ($m = 2$), what is the total number of conversion periods $n$?",o:["3","4","6","8"],a:2},
  {type:"mc",q:"If $t = 2$ years and interest is compounded quarterly ($m = 4$), what is $n$?",o:["6","8","10","4"],a:1},
  {type:"mc",q:"If $t = 5$ years and interest is compounded monthly ($m = 12$), what is $n$?",o:["17","36","48","60"],a:3},
  {type:"mc",q:"The nominal rate, denoted by $j$, is best described as:",o:["The interest rate per period","The rate charged that may be converted several times per year","The total interest earned over the entire term","The discount rate applied to the maturity value"],a:1},
  {type:"mc",q:"The interest rate per period $i$ is obtained from the nominal rate $j$ and frequency $m$ by:",o:["$i = jm$","$i = j - m$","$i = \\frac{j}{m}$","$i = \\frac{m}{j}$"],a:2},
  {type:"mc",q:"If the nominal rate $j = 12\\%$ and interest is compounded semiannually ($m = 2$), what is the interest rate per period $i$?",o:["3%","6%","12%","24%"],a:1},
  {type:"mc",q:"If the nominal rate $j = 14\\%$ and interest is compounded quarterly ($m = 4$), what is $i$?",o:["2%","3%","3.5%","7%"],a:2},
  {type:"mc",q:"If the nominal rate $j = 16\\%$ and interest is compounded monthly ($m = 12$), what is $i$ approximately?",o:["0.5%","1%","1.33%","2%"],a:2},
  {type:"mc",q:"The accumulated value of the principal $P$ at the end of the compound interest term is called the:",o:["Present value","Simple interest","Compound amount","Discount"],a:2},
  {type:"mc",q:"The formula for compound amount $F$ at the end of $n$ periods is:",o:["$F = P(1 - i)^n$","$F = P(1 + i)^n$","$F = P + in$","$F = \\frac{P}{(1+i)^n}$"],a:1},
  {type:"mc",q:"In the compound amount formula $F = P(1+i)^n$, what does $i$ represent?",o:["Nominal rate","Frequency of conversion","Interest rate per period","Total number of conversion periods"],a:2},
  {type:"mc",q:"In the compound amount formula $F = P(1+i)^n$, what does $n$ represent?",o:["Number of years","Nominal rate","Interest rate per period","Total number of conversion periods"],a:3},
  {type:"mc",q:"The formula for Compound Interest $I_c$ (total interest earned) is:",o:["$I_c = F + P$","$I_c = F - P$","$I_c = P(1+i)^n$","$I_c = \\frac{F}{P}$"],a:1},
  {type:"mc",q:"If $P = $ ₱12,900, $j = 3\\%$ compounded semiannually, and $t = 4$ years, what is $i$?",o:["3%","1.5%","6%","0.75%"],a:1},
  {type:"mc",q:"If $P = $ ₱12,900, $j = 3\\%$ compounded semiannually, and $t = 4$ years, what is $n$?",o:["4","6","8","12"],a:2},
  {type:"mc",q:"If $P = $ ₱12,900, $i = 0.015$, and $n = 8$, what is the compound amount $F$? (nearest centavo)",o:["₱14,000.00","₱14,531.75","₱13,500.00","₱15,000.00"],a:1},
  {type:"mc",q:"Using $F = $ ₱14,531.75 and $P = $ ₱12,900, what is the compound interest $I_c$?",o:["₱1,500.00","₱1,631.75","₱1,200.00","₱1,731.75"],a:1},
  {type:"mc",q:"If $t = 20$ months and interest is compounded monthly ($m = 12$), what is $n$?",o:["12","16","20","24"],a:2},
  {type:"mc",q:"If $P = $ ₱30,000, $j = 16\\%$ compounded semiannually, and $t = 3.5$ years, what is $n$?",o:["6","7","8","9"],a:1},
  {type:"mc",q:"If $P = $ ₱30,000, $i = 0.08$, and $n = 7$, the compound amount $F$ is approximately:",o:["₱45,000.00","₱51,414.73","₱48,000.00","₱53,000.00"],a:1},
  {type:"mc",q:"Present Value in compound interest refers to:",o:["The compound amount at the end of the term","The value of a certain sum of money at the present time","The total interest earned over the term","The nominal rate times the principal"],a:1},
  {type:"mc",q:"The formula for Present Value $P$ in compound interest is:",o:["$P = F(1+i)^n$","$P = F(1+i)^{-n}$","$P = F - I_c$","$P = F(1-i)^n$"],a:1},
  {type:"mc",q:"If $F = $ ₱35,000, $j = 12\\%$ compounded quarterly, and $t = 7.5$ years, what is $i$?",o:["6%","4%","3%","12%"],a:2},
  {type:"mc",q:"If $F = $ ₱35,000, $j = 12\\%$ compounded quarterly, and $t = 7.5$ years, what is $n$?",o:["25","28","30","32"],a:2},
  {type:"mc",q:"If $F = $ ₱35,000, $i = 0.03$, and $n = 30$, the present value $P$ is approximately:",o:["₱12,000.00","₱14,419.54","₱16,000.00","₱18,000.00"],a:1},
  {type:"mc",q:"If $F = $ ₱94,500, $j = 6\\%$ compounded semiannually, and $t = 3$ years, the present value $P$ is approximately:",o:["₱75,000.00","₱79,142.26","₱82,000.00","₱85,000.00"],a:1},
  {type:"mc",q:"A stock is defined as:",o:["A certificate promising to pay a specified amount plus interest at a future date","A type of security that signifies ownership in a corporation and represents a claim on part of the corporation's assets and earnings","A deduction from the maturity amount of an obligation","A fund that pays compound interest monthly"],a:1},
  {type:"mc",q:"Stocks in the Philippines are traded at which of the following marketplaces?",o:["NYSE and NASDAQ","PSE and MSE","BSP and SEC","BPI and BDO"],a:1},
  {type:"mc",q:"A bond is best described as:",o:["A type of security signifying ownership in a corporation","A certificate or written contract in which the debtor promises to pay its holder a specified amount plus interest at a stated future date","A stock that receives cumulative dividends","A type of mutual fund"],a:1},
  {type:"mc",q:"The par value or face value of a bond is:",o:["The market price of the bond","The principal borrowed as stated in the bond","The annual interest payment","The premium above par value"],a:1},
  {type:"mc",q:"A bond is said to be sold at premium when:",o:["Sold at a price equal to the face value","Sold at a price less than the face value","Sold at a price higher than its face or par value","Sold to a government entity"],a:2},
  {type:"mc",q:"A bond is bought at a discount when:",o:["Bought at par value","Bought at a price higher than par value","Bought for less than its par value","Bought at 110% of par value"],a:2},
  {type:"mc",q:"Dividends are defined as:",o:["The interest paid on bonds","The distribution of a company's profits to its shareholders","The par value of each share","The broker's commission on stock transactions"],a:1},
  {type:"mc",q:"Shareholders are defined as:",o:["Licensed brokers in the stock market","Persons who own shares of stocks in a corporation","Bond issuers","Corporate debtors"],a:1},
  {type:"mc",q:"Preferred stocks is a class of corporate stock in which the investor has:",o:["Voting rights and shares directly in the success or failure of the business","Preferential rights over common shareholders to dividends and a company's assets","No rights to dividends","Only the right to sell bonds"],a:1},
  {type:"mc",q:"Common stocks is a class of corporate stock in which the investor has:",o:["Preferential rights to dividends over preferred shareholders","Voting rights and shares directly in the success or failure of the business","Guaranteed fixed dividends","Rights only to bond interest"],a:1},
  {type:"mc",q:"A no-par value stock is a stock that:",o:["Has a very high par value","Does not have a par value and the dividend is quoted as a peso amount per share","Always pays cumulative dividends","Can only be traded at the PSE"],a:1},
  {type:"mc",q:"Cumulative preferred stock is a type of preferred stock that:",o:["Receives a dividend only when declared","Receives a dividend each year","Can be converted to bonds","Has no voting rights and no dividends"],a:1},
  {type:"mc",q:"Dividend in arrears is best described as:",o:["Extra dividends paid when the company performs well","The amount of dividends that accumulate and are owed to cumulative preferred shareholders for past years in which no dividends are paid","The annual dividend rate for common stock","The broker's commission on dividends"],a:1},
  {type:"mc",q:"Nonparticipating stock means that shareholders:",o:["May receive additional dividends if the company performs well","Receive only fixed dividends","Can convert shares to bonds","Have preferential rights over all creditors"],a:1},
  {type:"mc",q:"Participating stock means that shareholders:",o:["Receive only fixed dividends","May receive additional dividends if the company performs well","Have no voting rights","Are guaranteed repayment at maturity"],a:1},
  {type:"mc",q:"Convertible preferred stock means:",o:["The stock pays dividends in foreign currency","The stock may be exchanged for a specified number of common shares in the future","The stock is redeemable at par","The stock has no par value"],a:1},
  {type:"mc",q:"The formula for Dividend per share (common) is:",o:["$\\frac{\\text{Total preferred dividend}}{\\text{Number of shares (common)}}$","$\\frac{\\text{Total common dividend}}{\\text{Number of shares (common)}}$","$Par\\ value \\times Dividend\\ rate$","$\\text{Number of shares} \\times \\text{Dividend per share}$"],a:1},
  {type:"mc",q:"The formula for Total preferred dividend is:",o:["$\\text{Total dividend} - \\text{Total common dividend}$","$\\frac{\\text{Total common dividend}}{\\text{Number of shares}}$","$\\text{Number of shares} \\times \\text{Dividend per share}$","$Par\\ value \\times Dividend\\ rate \\times t$"],a:2},
  {type:"mc",q:"The formula for Total common dividend is:",o:["$\\text{Total dividend} - \\text{Total preferred dividend}$","$\\text{Number of shares} \\times \\text{Dividend per share}$","$Par\\ value \\times Dividend\\ rate$","$\\frac{\\text{Total preferred dividend}}{\\text{Number of shares}}$"],a:0},
  {type:"mc",q:"The formula for Dividend per share (preferred) is:",o:["$\\frac{\\text{Total common dividend}}{\\text{Number of shares}}$","$Par\\ value \\times Dividend\\ rate$","$\\text{Total dividend} - \\text{Total preferred dividend}$","$\\frac{\\text{Annual interest}}{\\text{Price of bond}}$"],a:1},
  {type:"mc",q:"Stock Valuation is defined as:",o:["The process of calculating the values of goods or materials owned by a company or available for sale at a particular time","The formula for computing compound interest","The method of determining discount on bonds","The rate at which dividends are paid to preferred shareholders"],a:0},
  {type:"mc",q:"The Current Yield for a stock is computed using which formula?",o:["$\\frac{\\text{Current price per share}}{\\text{Annual dividend per share}}$","$\\frac{\\text{Annual dividend per share}}{\\text{Current price per share}}$","$\\frac{\\text{Earnings per share}}{\\text{Current price per share}}$","$\\frac{\\text{Total dividend}}{\\text{Number of shares}}$"],a:1},
  {type:"mc",q:"If a stock pays no dividend, the current yield is:",o:["Equal to the par value","Equal to the bond rate","There is no current yield","Equal to 100%"],a:2},
  {type:"mc",q:"The Price-Earnings Ratio of a stock is found using which formula?",o:["$\\frac{\\text{Earnings per share}}{\\text{Current price per share}}$","$\\frac{\\text{Annual dividend per share}}{\\text{Current price per share}}$","$\\frac{\\text{Current price per share}}{\\text{Earnings per share}}$","$\\frac{\\text{Total dividend}}{\\text{Number of shares}}$"],a:2},
  {type:"mc",q:"If the current price per share is ₱2,685 and earnings per share is ₱89.50, what is the price-earnings ratio?",o:["25","28","30","35"],a:2},
  {type:"mc",q:"A round lot in stock transactions refers to:",o:["Any number of shares less than 100","A multiple of 100 shares","Exactly 50 shares","Any number of shares above 500"],a:1},
  {type:"mc",q:"An odd lot in stock transactions refers to:",o:["A multiple of 100 shares","Less than 100 shares","Exactly 200 shares","More than 1,000 shares"],a:1},
  {type:"mc",q:"Proceeds from selling stock are computed as:",o:["Value of shares + Total Broker's commission","Value of shares - Total Broker's commission","Cost of shares + Broker's commission","Total dividend - Total cost"],a:1},
  {type:"mc",q:"Gain (or loss) on a stock transaction is computed as:",o:["Proceeds - Total Cost","Total Cost - Proceeds","Value of shares - Par value","Annual dividend - Current yield"],a:0},
  {type:"mc",q:"A stockbroker is best described as:",o:["A person who issues bonds on behalf of the government","A professional in stock market trading who acts as an agent in the selling and buying of stocks or other securities","The manager of a corporation's preferred stock","A bondholder who receives periodic coupon payments"],a:1},
  {type:"mc",q:"The stockbroker's commission is:",o:["The par value of each share","The fee charged for assisting in the purchase or sale of shares of stocks; percent of the cost of the stock transaction","The annual dividend rate","The discount on bonds"],a:1},
  {type:"mc",q:"Bond Valuation is defined as:",o:["The process of computing simple interest on bonds","A technique for determining the fair value of a particular bond","The method of computing dividends on preferred stock","The formula used to find the present value of an annuity"],a:1},
  {type:"mc",q:"The Current Yield of a Bond is computed by:",o:["Dividing the par value by the coupon payment","Dividing the annual interest by the purchase price of a bond","Multiplying the face value by the bond rate","Dividing the market price by the face value"],a:1},
  {type:"mc",q:"The formula for the Current Yield of a Bond is:",o:["$\\frac{\\text{Price of Bond}}{\\text{Annual Interest}}$","$\\frac{\\text{Annual Interest}}{\\text{Price of Bond}}$","$\\frac{\\text{Face Value}}{\\text{Coupon Payment}}$","$\\frac{\\text{Nominal Rate}}{\\text{Frequency of Conversion}}$"],a:1},
  {type:"mc",q:"In bond valuation notation, $V$ represents:",o:["Face value or par value of the bond","Redemption value of bond","Price of a bond","Nominal interest rate"],a:1},
  {type:"mc",q:"In bond valuation notation, $F$ represents:",o:["Redemption value","Face value or par value of the bond","Price of a bond","Coupon Payment"],a:1},
  {type:"mc",q:"In bond valuation notation, $r$ represents:",o:["Nominal interest rate","Periodic interest rate","Bond rate","Number of conversions per year"],a:2},
  {type:"mc",q:"In bond valuation notation, $k$ represents:",o:["Bond rate","Nominal interest rate","Coupon Payment","Redemption value"],a:2},
  {type:"mc",q:"The Coupon Payment $k$ from a bond is computed as:",o:["$k = F \\times i$","$k = F \\times b$","$k = V \\times i$","$k = V \\times j$"],a:1},
  {type:"mc",q:"The formula for the Price of a Bond using the General Method is:",o:["$P = V(1+i)^n + k\\left[\\frac{1-(1+i)^n}{i}\\right]$","$P = V(1+i)^{-n} + k\\left[\\frac{1-(1+i)^{-n}}{i}\\right]$","$P = F(1+i)^{-n}$","$P = k\\left[\\frac{1-(1+i)^{-n}}{i}\\right] - V(1+i)^{-n}$"],a:1},
  {type:"mc",q:"If a bond is redeemable at 110%, and the face value is ₱3,200, what is the redemption value $V$?",o:["₱3,200","₱3,320","₱3,520","₱3,840"],a:2},
  {type:"mc",q:"In bond valuation notation, $b$ represents:",o:["Bond rate","Coupon Payment","Periodic bond interest rate","Nominal interest rate"],a:2},
  {type:"mc",q:"In bond valuation notation, $i$ represents:",o:["Bond rate","Coupon Payment","Periodic bond interest rate","Periodic interest rate"],a:3},

  // ===== NEW SOLVING MCQs =====
  // Simple Discount Solving
  {type:"mc",q:"Find the discount $D$ on ₱2,000 due in $t = \\frac{1}{4}$ year at $d = 5\\%$ simple discount.",o:["₱20","₱25","₱50","₱100"],a:1},
  {type:"mc",q:"Find the present value $P$ of ₱2,000 due in $t = \\frac{1}{4}$ year at $d = 5\\%$ simple discount.",o:["₱1,900","₱1,950","₱1,975","₱2,025"],a:2},
  {type:"mc",q:"If $D = $ ₱25, $F = $ ₱2,000, and $t = \\frac{1}{4}$ year, what is the discount rate $d$?",o:["3%","4%","5%","6%"],a:2},

  // Ordinary and Exact Interest Solving
  {type:"mc",q:"Find the Ordinary Interest using Actual Time ($d = 155$ days) on ₱28,700 at $r = 7.3\\%$. Use $I_o = Pr\\frac{d}{360}$.",o:["₱872.48","₱884.60","₱889.70","₱902.06"],a:3},
  {type:"mc",q:"Find the Ordinary Interest using Approximate Time ($d = 152$ days) on ₱28,700 at $r = 7.3\\%$. Use $I_o = Pr\\frac{d}{360}$.",o:["₱872.48","₱884.60","₱889.70","₱902.06"],a:1},
  {type:"mc",q:"Find the Exact Interest using Actual Time ($d = 155$ days) on ₱28,700 at $r = 7.3\\%$. Use $I_e = Pr\\frac{d}{365}$.",o:["₱872.48","₱884.60","₱889.70","₱902.06"],a:2},
  {type:"mc",q:"Find the Exact Interest using Approximate Time ($d = 152$ days) on ₱28,700 at $r = 7.3\\%$. Use $I_e = Pr\\frac{d}{365}$.",o:["₱872.48","₱884.60","₱889.70","₱902.06"],a:0},

  // Dividend Solving
  {type:"mc",q:"AUS Enterprises has 1,500,000 shares of common stock. If total dividends declared is ₱30,000,000, what is the dividend per share?",o:["₱10","₱15","₱20","₱25"],a:2},
  {type:"mc",q:"SSS Inc. has 40,000 preferred shares paying ₱60 per share. What is the total preferred dividend?",o:["₱1,200,000","₱2,400,000","₱3,600,000","₱4,800,000"],a:1},
  {type:"mc",q:"If total dividends declared is ₱18,000,000 and total preferred dividend is ₱2,400,000, what is the total common dividend?",o:["₱13,600,000","₱15,600,000","₱16,200,000","₱20,400,000"],a:1},
  {type:"mc",q:"Using total common dividend of ₱15,600,000 and 80,000 common shares, what is the dividend per share of common stock?",o:["₱150","₱175","₱195","₱210"],a:2},
  {type:"mc",q:"A preferred stock has a par value of ₱2,000 and a dividend rate of 5%. What is the dividend per share?",o:["₱50","₱75","₱100","₱125"],a:2},
  {type:"mc",q:"Neri Corporation has 70,000 cumulative preferred shares at ₱100 dividend per share. No dividend was paid last year. What is the total preferred dividend including arrears?",o:["₱3,500,000","₱7,000,000","₱10,500,000","₱14,000,000"],a:3},
  {type:"mc",q:"If total dividends is ₱25,000,000 and total preferred dividend (with arrears) is ₱14,000,000, and there are 250,000 common shares, what is the dividend per share of common stock?",o:["₱33","₱40","₱44","₱50"],a:2},

  // Stock Valuation Solving
  {type:"mc",q:"MMDN Corporation paid a dividend of ₱142.60 per share. If the current price per share is ₱2,300, what is the current yield?",o:["5.0%","5.8%","6.2%","7.0%"],a:2},
  {type:"mc",q:"A stock pays a dividend of ₱70 per year and is currently selling at ₱1,400 per share. What is the current yield?",o:["3%","4%","5%","6%"],a:2},
  {type:"mc",q:"SSS stock has a current price of ₱2,464 and annual net income per share of ₱88. What is the price-earnings ratio?",o:["25","26","27","28"],a:3},

  // Cost, Proceeds, Gain Solving
  {type:"mc",q:"Shiela purchases 250 shares at ₱3,500 per share. What is the cost of shares (before broker's commission)?",o:["₱750,000","₱800,000","₱875,000","₱900,000"],a:2},
  {type:"mc",q:"On a purchase of 250 shares at ₱3,500, the broker charges 3% on 200 round-lot shares and 4% on 50 odd-lot shares. What is the total broker's commission on purchase?",o:["₱21,000","₱24,500","₱28,000","₱35,000"],a:2},
  {type:"mc",q:"Using total cost of shares ₱875,000 and total broker's commission of ₱28,000, what is the total cost of purchasing the stock?",o:["₱875,000","₱893,000","₱903,000","₱910,000"],a:2},
  {type:"mc",q:"Shiela sells 250 shares at ₱4,000. The broker charges 3% on 200 round-lot shares and 4% on 50 odd-lot shares on the sale. What are the proceeds from selling?",o:["₱950,000","₱960,000","₱968,000","₱975,000"],a:2},
  {type:"mc",q:"If the proceeds from selling stock are ₱968,000 and the total cost of purchasing was ₱903,000, what is the gain (or loss) on the transaction?",o:["₱55,000 gain","₱60,000 gain","₱65,000 gain","₱70,000 gain"],a:2},

  // Bond Valuation Solving
  {type:"mc",q:"A ₱3,200 bond has a bond rate $r = 9\\%$ compounded quarterly. What is the periodic bond interest rate $b = \\frac{r}{m}$?",o:["1.5%","2%","2.25%","3%"],a:2},
  {type:"mc",q:"A ₱3,200 bond has $b = 0.0225$. What is the coupon payment $k = Fb$?",o:["₱54","₱62","₱72","₱80"],a:2},
  {type:"mc",q:"A bond with face value ₱14,500 pays yearly interest at 12%. What is the current yield when purchased at par (₱14,500)?",o:["10%","11%","12%","13%"],a:2},
  {type:"mc",q:"A bond with face value ₱14,500 pays yearly interest at 12%. What is the current yield when purchased at ₱13,920?",o:["11.5%","12%","12.5%","13%"],a:2},
  {type:"mc",q:"A ₱3,200 bond at 9% pays coupons quarterly, redeemed at par, with $i = 0.02$, $n = 16$, and $k = 72$. Using $P = V(1+i)^{-n} + k\\left[\\frac{1-(1+i)^{-n}}{i}\\right]$, what is the price of the bond (nearest centavo)?",o:["₱3,100.00","₱3,200.00","₱3,308.62","₱3,541.72"],a:2},
  {type:"mc",q:"If the same ₱3,200 bond is redeemable at 110% ($V = $ ₱3,520) with $i = 0.02$, $n = 16$, $k = 72$, what is the price of the bond?",o:["₱3,200.00","₱3,308.62","₱3,420.00","₱3,541.72"],a:3},

  // ===== True or False (12) =====
  {type:"tf",q:"Simple Interest is a fixed percentage of the principal paid each year the principal is left on deposit.",a:true},
  {type:"tf",q:"The maturity value formula is $F = P - I$.",a:false},
  {type:"tf",q:"Discount $D$ is a deduction from the maturity amount $F$ of an obligation allowed for paying it currently.",a:true},
  {type:"tf",q:"Approximate Time assumes there are 31 days in each month.",a:false},
  {type:"tf",q:"Exact Interest is computed based on 365 days in a year.",a:true},
  {type:"tf",q:"Ordinary Interest uses 360 days as the basis for one year.",a:true},
  {type:"tf",q:"Compound Interest is computed on the original principal only, not on accumulated interest.",a:false},
  {type:"tf",q:"The total number of conversion periods $n$ is computed as $n = tm$, where $t$ is time in years and $m$ is the frequency of conversion.",a:true},
  {type:"tf",q:"The interest rate per period $i$ is obtained by multiplying the nominal rate $j$ by the frequency of conversion $m$.",a:false},
  {type:"tf",q:"A bond sold at par is sold at a price equal to the face or par value.",a:true},
  {type:"tf",q:"Preferred stocks give investors voting rights and a share in the success or failure of the business.",a:false},
  {type:"tf",q:"The price-earnings ratio is computed by dividing the current price per share by the earnings per share.",a:true}
];